roles/setup_repo/defaults/main.yml
roles/setup_repo/tasks/EPAS_rhel_setuprepos.yml
roles/setup_repo/tasks/PG_rhel_setuprepos.yml

Related to https://github.com/EnterpriseDB/edb-ansible/issues/17

Download EPEL repo. v8 GPG key

---

roles/setup_repo/defaults/main.yml
roles/setup_repo/tasks/EPAS_rhel_setuprepos.yml
roles/setup_repo/tasks/PG_rhel_setuprepos.yml

Download EDB and PGDG repo. GPG key

---

README.md
roles/init_dbserver/README.md
roles/install_dbserver/README.md
roles/manage_dbserver/README.md
roles/manage_pgbouncer_databases/README.md
roles/manage_pgbouncer_users/README.md
roles/setup_efm/README.md
roles/setup_pem/README.md
roles/setup_pgbouncer/README.md
roles/setup_replication/README.md
roles/setup_repo/README.md

Improve consistency of roles' README.md file

---

roles/manage_pgbouncer_databases/README.md
roles/manage_pgbouncer_databases/defaults/main.yml
roles/manage_pgbouncer_databases/tasks/pgbouncer_set_databases.yml
roles/manage_pgbouncer_databases/templates/databases.ini.template
roles/manage_pgbouncer_users/README.md
roles/manage_pgbouncer_users/tasks/pgbouncer_set_userlist.yml
roles/manage_pgbouncer_users/templates/userlist.txt.template
roles/setup_pgbouncer/tasks/pgbouncer_setup.yml

The `lineinfile` module provides more fine grained lines management than the "replace the whole file or nothing" approach provided by `template` module usage.

Improve PgBouncer databases and users management

---

roles/manage_pgbouncer_databases/tasks/pgbouncer_set_databases.yml
roles/manage_pgbouncer_users/tasks/pgbouncer_set_userlist.yml
roles/setup_pgbouncer/tasks/pgbouncer_setup.yml

Fix linting issues with pgbouncer roles

---

roles/setup_pem/tasks/main.yml
roles/setup_pem/tasks/setup_pemagent.yml
roles/setup_pem/tasks/setup_pemserver.yml

@jt-edb 
Can you please validate the changes in this PR? We are planning to release these changes today. This change is also important for the Proof of Technology work.
Thank you!

Fixing python issues with edb-ansible

---

roles/setup_pem/tasks/main.yml

Fixing the ansible liniting issue

---

galaxy.yml
roles/manage_dbserver/tasks/generate_password.yml
roles/manage_dbserver/tasks/manage_pgpass.yml
roles/setup_efm/tasks/efm_create_properties.yml
roles/setup_pem/tasks/pem_agent_config.yml
roles/setup_pem/tasks/pem_agent_register_db.yml
roles/setup_replication/tasks/C07-RH07-os-tune.yml

Ansible lint fixes

---

roles/setup_efm/README.md
roles/setup_efm/defaults/main.yml
roles/setup_replication/defaults/main.yml
roles/setup_replication/tasks/setup_replication.yml

Made changes as per the privious suggesstion

---

.github/workflows/push.yml
README.md

Run ansible-lint on push and PR using GH actions

---

roles/init_dbserver/tasks/init_dbserver.yml
roles/setup_efm/defaults/main.yml
roles/setup_efm/tasks/efm_configure.yml
roles/setup_efm/tasks/setup_efm.yml
roles/setup_pemserver/tasks/setup_pemserver.yml
roles/setup_pgbouncer/tasks/pgbouncer_setup.yml
roles/setup_pgpool2/tasks/pgpool2_setup.yml
roles/setup_replication/tasks/setup_replication.yml

Changes:
- Open the ports using firewalld only if the service is enabled and started
- Open Postgres port
- Open EFM ports
- Open PEM server port

Improve firewalld usage

---

README.md
playbook.yml
roles/autotuning/README.md
roles/autotuning/defaults/main.yml
roles/autotuning/meta/main.yml
roles/autotuning/tasks/autotuning.yml
roles/autotuning/tasks/install_tuned.yml
roles/autotuning/tasks/main.yml
roles/autotuning/tasks/setup_tuned.yml
roles/autotuning/tasks/tune_postgres.yml
roles/autotuning/templates/tuned.conf.template
roles/autotuning/vars/EPAS.yml
roles/autotuning/vars/PG.yml
vars_plugins/host_supported_roles.py

Auto-tuning role

---

roles/setup_pgpool2/tasks/setup_pgpool2.yml
roles/setup_replication/tasks/upstream_node_slots.yml

* Use private_ip in PgPoolII backend configuration
* Avoid concurrency issue when updating primary HBA

Some fixes

---

Makefile

Make sure we fetch only the first line of the VERSION file.

Improve version detection

---

roles/init_dbserver/README.md
roles/init_dbserver/templates/postgresql.conf.template
roles/manage_pgbouncer/README.md
roles/manage_pgpool2/README.md
roles/setup_barman/README.md
roles/setup_barmanserver/README.md
roles/setup_efm/README.md
roles/setup_efm/tasks/efm_create_properties.yml
roles/setup_efm/templates/efm_db_functions.3.10.template
roles/setup_efm/templates/efm_db_functions.4.0.template
roles/setup_efm/templates/efm_db_functions.4.1.template
roles/setup_pemagent/README.md
roles/setup_pemserver/README.md
roles/setup_pgbouncer/README.md
roles/setup_pgpool2/README.md
roles/setup_replication/README.md

With this PR adding the following:
1. Adding efm_db_functions template and adding the tasks to push the changes with the deployment.
2. Adding wal_keep_segments/wal_keep_size default value.
3. fixing the readme to use edb_devops.edb_postgres instead of edb_devops.postgres which doesn't exist.

EFM db functions and wal_keep_segments/wal_keep_size update

---

roles/setup_pgpool2/tasks/pgpool2_configure_backends.yml
roles/setup_pgpool2/tasks/setup_pgpool2.yml

Making sure backend_application_nameX taking the PGAPPNAME used in streaming replication

pgpool parameter backend_application_nameX update

---

roles/manage_dbserver/tasks/manage_db.yml

The error was: ProgrammingError: template database
"line_item.template | default('template0')" does not exist

Fixes DB creation

---

plugins/lookup/pg_sr_cluster_nodes.py

Handle the case when there is no standby nodes.

pg_sr_cluster_nodes improvement

---

roles/setup_pemagent/tasks/rm_pemagent.yml

Adding missing rm_pemagent.yml tasks in pemagent

Adding missing rm_pemagent.yml tasks in pemagent

---

roles/setup_pgpool2/tasks/pgpool2_install.yml
roles/setup_pgpool2/tasks/pgpool2_setup.yml
roles/setup_pgpool2/tasks/setup_pgpool2.yml

Fix the "is true" cases

---

roles/init_dbserver/defaults/main.yml
roles/manage_dbserver/defaults/main.yml
roles/setup_efm/defaults/main.yml
roles/setup_efm/tasks/setup_efm.yml
roles/setup_pemagent/defaults/main.yml
roles/setup_pemserver/defaults/main.yml
roles/setup_replication/defaults/main.yml

Adding support for EFM 4.2

---

roles/init_dbserver/defaults/main.yml
roles/setup_efm/defaults/main.yml
roles/setup_efm/tasks/efm_configure.yml
roles/setup_efm/tasks/setup_efm.yml
roles/setup_pemagent/defaults/main.yml
roles/setup_pemserver/defaults/main.yml
roles/setup_replication/defaults/main.yml
roles/setup_replication/tasks/upstream_node.yml
roles/setup_replication/vars/EPAS_Debian.yml
roles/setup_replication/vars/EPAS_RedHat.yml
roles/setup_replication/vars/PG_Debian.yml
roles/setup_replication/vars/PG_RedHat.yml

Updating the roles for hostnames fixes

Hostname fixes

---

roles/setup_pemagent/defaults/main.yml
roles/setup_pemagent/tasks/pem_agent_hba.yml
roles/setup_pemagent/tasks/pem_agent_register_db.yml
roles/setup_pemagent/tasks/setup_pemagent.yml

Allow the pemagent to be installed on non-dbservers

Allow the pemagent to be installed on non-dbservers

---

roles/setup_repo/README.md
roles/setup_repo/defaults/main.yml
roles/setup_repo/tasks/PG_Debian_rm_repos.yml
roles/setup_repo/tasks/PG_Debian_setuprepos.yml
roles/setup_repo/tasks/PG_RedHat_rm_repos.yml
roles/setup_repo/tasks/PG_RedHat_setuprepos.yml

Support of additional package repositories

---

roles/autotuning/vars/EPAS.yml
roles/init_dbserver/vars/EPAS_RedHat.yml
roles/manage_dbserver/vars/EPAS_RedHat.yml
roles/setup_efm/vars/EPAS_Debian.yml
roles/setup_efm/vars/EPAS_RedHat.yml
roles/setup_pemagent/vars/EPAS.yml
roles/setup_pemserver/vars/EPAS.yml
roles/setup_replication/vars/EPAS_RedHat.yml

Fix EPAS unix socket path to /var/run/edb/asXX

---

roles/setup_pemagent/defaults/main.yml
roles/setup_pemagent/tasks/setup_pemagent.yml

Adding the ability to register DB through pgbouncer

Pgbouncer db register

---

roles/manage_dbserver/tasks/manage_dbserver.yml
roles/manage_dbserver/tasks/manage_profile.yml
roles/manage_dbserver/tasks/manage_psqlrc.yml
roles/manage_dbserver/vars/EPAS_Debian.yml
roles/manage_dbserver/vars/EPAS_RedHat.yml
roles/manage_dbserver/vars/PG_Debian.yml
roles/manage_dbserver/vars/PG_RedHat.yml

Shell profile and .psqlrc files deployment

---

roles/init_dbserver/tasks/pg_initdb.yml

Fixing the initdbserver issue for debian os_family

Fixing the initdbserver issue for debian os_family

---

roles/init_dbserver/tasks/pg_initdb.yml
roles/manage_dbserver/vars/EPAS_Debian.yml
roles/manage_dbserver/vars/EPAS_RedHat.yml
roles/manage_dbserver/vars/PG_Debian.yml
roles/manage_dbserver/vars/PG_RedHat.yml
roles/setup_replication/tasks/rm_replication.yml

Merging changes requires for fixing the issue with pg_initdb for debian

Bug fixes for Debian pg_initdb

---

roles/setup_pemagent/tasks/pem_agent_config.yml
roles/setup_pemserver/tasks/pem_server_config.yml

Make sure pemagent and pemagent services are enabled. This fixes the issue with the restart of the server

Ensure pemagent and pemserver services are enabled

---

roles/setup_barman/README.md
roles/setup_barman/templates/barman.postgres.template
roles/setup_barman/templates/barman.rsync.template

Author: Cédric Villemain <Cedric.Villemain@Data-Bene.io>

setup_barman: adding the get_wal recovery option

---

roles/setup_barman/defaults/main.yml
roles/setup_barman/tasks/setup_barman.yml
roles/setup_barmanserver/defaults/main.yml
roles/setup_barmanserver/tasks/install_packages.yml

Author: Cédric Villemain <Cedric.Villemain@Data-Bene.io>
Fixes #232

Barman installation on Debian

---

roles/autotuning/defaults/main.yml
roles/autotuning/tasks/autotuning.yml
roles/autotuning/tasks/install_tuned.yml
roles/autotuning/tasks/setup_tuned.yml
roles/autotuning/tasks/tune_postgres.yml
roles/autotuning/vars/EPAS_Debian.yml
roles/autotuning/vars/EPAS_RedHat.yml
roles/autotuning/vars/PG_Debian.yml
roles/autotuning/vars/PG_RedHat.yml

Author: Cédric Villemain <Cedric.Villemain@Data-Bene.io>
Minor improvements by me.
Fixes #233

Autotuning support on Debian

---

roles/setup_barmanserver/tasks/create_user.yml

Fix barman server setup when getenforce is absent

---

plugins/lookup/pem_server.py

From the inventory when pem_server_private_ip is not defined for
the current host.

Returns the first pemserver entry found

---

tests/.gitignore
tests/cases/setup_replication/Makefile
tests/cases/setup_replication/docker-compose.yml
tests/cases/setup_replication/inventory.yml.j2
tests/cases/setup_replication/playbook.yml
tests/cases/setup_replication/vars.json
tests/config.yml
tests/tests/conftest.py
tests/tests/test_manage_dbserver.py
tests/tests/test_setup_replication.py

testing for the setup_replication role

Setup replication testing framework

---

.github/workflows/push.yml
tests/cases/manage_pgbouncer/Makefile
tests/cases/manage_pgbouncer/docker-compose.yml
tests/cases/manage_pgbouncer/inventory.yml.j2
tests/cases/manage_pgbouncer/playbook.yml
tests/cases/manage_pgbouncer/vars.json
tests/config.yml
tests/tests/test_manage_pgbouncer.py

- test_db is successfully created
- pid file is successfully created and in the correct path
- auth file is successfully created and in the correct path
- correct number of pgbouncer users is created

manage_pgbouncer testing framework

---

roles/setup_barmanserver/tasks/install_packages.yml
tests/cases/setup_barmanserver/Makefile
tests/cases/setup_barmanserver/docker-compose.yml
tests/cases/setup_barmanserver/inventory.yml.j2
tests/cases/setup_barmanserver/playbook.yml
tests/cases/setup_barmanserver/vars.json
tests/config.yml
tests/tests/test_setup_barmanserver.py

- Check to see if barman packages were successfully installed
- Check to see if barman config file was successfully created
- Check to see if barman is a sudo user

Setup barmanserver testing framework

---

roles/setup_dbt2/tasks/dbt2_update_pg_hba.yml
roles/setup_dbt2/tasks/main.yml
roles/setup_dbt2_client/tasks/main.yml
roles/setup_dbt2_driver/tasks/main.yml

- Increase fd limits on the client node
- Remove unnecessary ansible code

DBT-2: improvements

---

.github/workflows/push.yml
tests/cases/setup_hammerdbserver/Makefile
tests/cases/setup_hammerdbserver/docker-compose.yml
tests/cases/setup_hammerdbserver/inventory.yml.j2
tests/cases/setup_hammerdbserver/playbook.yml
tests/cases/setup_hammerdbserver/vars.json
tests/config.yml
tests/tests/conftest.py
tests/tests/test_setup_hammerdbserver.py

- HammerDB tar file is downloaded
- HammerDB is successfully installed in root path

Setup hammerdbserver testing framework

---

playbook.yml
plugins/lookup/pem_agents.py
plugins/lookup/supported_roles.py
roles/install_dbserver/tasks/linux_coredump.yml
roles/setup_pemagent/defaults/main.yml
roles/setup_pemagent/tasks/linux_update_etc_hosts.yml
roles/setup_pemagent/tasks/pem_agent_barman_config.yml
roles/setup_pemagent/tasks/pem_agent_config.yml
roles/setup_pemagent/tasks/pem_agent_fetch_adm_password.yml
roles/setup_pemagent/tasks/pem_agent_hba.yml
roles/setup_pemagent/tasks/pem_agent_install.yml
roles/setup_pemagent/tasks/pem_agent_register_db.yml
roles/setup_pemagent/tasks/pem_agent_register_db_remote.yml
roles/setup_pemagent/tasks/pem_agent_user.yml
roles/setup_pemagent/tasks/rm_pemagent.yml
roles/setup_pemagent/tasks/setup_pemagent.yml
tests/cases/setup_pemagent/docker-compose.yml
tests/cases/setup_pemagent/inventory.yml.j2
tests/cases/setup_pemagent/playbook.yml

Adding pemagent support for barman

Adding pemagent support for barman

---

.github/workflows/push.yml
tests/cases/setup_dbt2_driver/Makefile
tests/cases/setup_dbt2_driver/docker-compose.yml
tests/cases/setup_dbt2_driver/inventory.yml.j2
tests/cases/setup_dbt2_driver/playbook.yml
tests/cases/setup_dbt2_driver/vars.json
tests/config.yml
tests/docker/Dockerfile.rocky8
tests/tests/conftest.py
tests/tests/test_setup_dbt2_driver.py

Tests include: 
- dbt2_driver packages are properly installed
- dbt_user is properly configured into env

Setup_dbt2_driver testing framework

---

roles/setup_pemagent/tasks/setup_pemagent.yml

Fixing an issue with capturing PEM Server version in setup pemagent

Fixing an issue with capturing PEM Server version in setup pemagent

---

.github/workflows/push.yml
tests/cases/setup_dbt2_client/Makefile
tests/cases/setup_dbt2_client/docker-compose.yml
tests/cases/setup_dbt2_client/inventory.yml.j2
tests/cases/setup_dbt2_client/playbook.yml
tests/cases/setup_dbt2_client/vars.json
tests/config.yml
tests/tests/conftest.py
tests/tests/test_setup_dbt2_client.py

- dbt2_client packages are properly installed
- nofile limits has been correctly increased for dbt2 user

Setup_dbt2_client testing framework

---

.github/workflows/push.yml
roles/setup_efm/tasks/prepare_hba_value_list.yml
roles/setup_pemagent/tasks/pem_agent_hba.yml
roles/setup_pgpool2/tasks/pgpool2_configure_backend_pg_hba.yml
roles/setup_pgpool2/tasks/pgpool2_configure_backends.yml
roles/setup_pgpool2/tasks/setup_pgpool2.yml
roles/setup_replication/tasks/prepare_hba_value_list.yml
roles/setup_repmgr/tasks/repmgr_prepare_hba.yml

Ansible 2.13 and forward does not permit to perform arithmetic and
concatenation operations outside of the jinja template.
Reported by: Stefan Fercot

Move arithmetic and concat. inside jinja template

---

roles/setup_barman/defaults/main.yml
roles/setup_barman/tasks/configure_barman.yml
roles/setup_barman/tasks/exchange_ssh_keys.yml
roles/setup_barman/tasks/post_configure_barman.yml
roles/setup_barman/tasks/update_barman_pgpass.yml
roles/setup_barmanserver/defaults/main.yml

Updating the default version of barman and also adding the initial capability of primary_vip in setup_barman

Primary VIP and Barman version

---

.github/workflows/push.yml
README.md
plugins/lookup/supported_roles.py
roles/setup_dbt3/README.md
roles/setup_dbt3/defaults/main.yml
roles/setup_dbt3/meta/main.yml
roles/setup_dbt3/tasks/dbt3_configure_profile.yml
roles/setup_dbt3/tasks/dbt3_install_packages.yml
roles/setup_dbt3/tasks/dbt3_tpc.yml
roles/setup_dbt3/tasks/main.yml
roles/setup_dbt3/templates/dbt3_profile
roles/setup_dbt3/vars/DBaaS.yml
roles/setup_dbt3/vars/EPAS.yml
roles/setup_dbt3/vars/PG.yml
tests/cases/setup_dbt3/Makefile
tests/cases/setup_dbt3/docker-compose.yml
tests/cases/setup_dbt3/inventory.yml.j2
tests/cases/setup_dbt3/playbook.yml
tests/cases/setup_dbt3/vars.json
tests/tests/test_setup_dbt3.py

This new playbook provides tasks to install and setup the dbt-3 kit.

Add playbooks for DBT-3

---

.github/workflows/push.yml
README.md
plugins/lookup/supported_roles.py
roles/setup_dbt7/README.md
roles/setup_dbt7/defaults/main.yml
roles/setup_dbt7/meta/main.yml
roles/setup_dbt7/tasks/dbt7_configure_profile.yml
roles/setup_dbt7/tasks/dbt7_install_packages.yml
roles/setup_dbt7/tasks/dbt7_tpc.yml
roles/setup_dbt7/tasks/main.yml
roles/setup_dbt7/templates/dbt7_profile
roles/setup_dbt7/vars/DBaaS.yml
roles/setup_dbt7/vars/EPAS.yml
roles/setup_dbt7/vars/PG.yml
tests/cases/setup_dbt7/Makefile
tests/cases/setup_dbt7/docker-compose.yml
tests/cases/setup_dbt7/inventory.yml.j2
tests/cases/setup_dbt7/playbook.yml
tests/cases/setup_dbt7/vars.json
tests/tests/test_setup_dbt7.py

Add playbooks for installing DBT-7, a TPC Benchmark(TM) DS fair-use implementation.

Add playbook for installing DBT-7

---

README.md
playbook.yml
plugins/lookup/supported_roles.py
roles/manage_dbpatches/README.md
roles/manage_dbpatches/defaults/main.yml
roles/manage_dbpatches/handlers/main.yml
roles/manage_dbpatches/meta/main.yml
roles/manage_dbpatches/tasks/apply_db_patches.yml
roles/manage_dbpatches/tasks/apply_primary_patches.yml
roles/manage_dbpatches/tasks/efm_cluster_primary.yml
roles/manage_dbpatches/tasks/main.yml
roles/manage_dbpatches/tasks/manage_dbpatches.yml
roles/manage_dbpatches/tasks/start_efm_pg_services.yml
roles/manage_dbpatches/tasks/start_user_defined_services.yml
roles/manage_dbpatches/tasks/stop_efm_pg_services.yml
roles/manage_dbpatches/tasks/stop_user_defined_services.yml
roles/manage_dbpatches/tasks/validate_efm_cluster.yml
roles/manage_dbpatches/vars/EPAS_Debian.yml
roles/manage_dbpatches/vars/EPAS_RedHat.yml
roles/manage_dbpatches/vars/PG_Debian.yml
roles/manage_dbpatches/vars/PG_RedHat.yml
roles/manage_dbpatches/vars/main.yml

Adding the first version of minor_patch updates based on efm role in the collection.

Adding first version of minor version updates for EFM cluster

---

README.md
roles/remove_cloudnativepg_sandbox/README.md
roles/remove_cloudnativepostgres_sandbox/README.md
roles/setup_cloudnativepg_sandbox/README.md
roles/setup_cloudnativepostgres_sandbox/README.md

- Updated 'README.md's for setup and remove CNP roles

Expanded 'CNP' documentation steps

---

tests/README.md
tests/cases/init_dbserver/docker-compose.yml
tests/cases/install_dbserver/docker-compose.yml
tests/cases/manage_dbserver/docker-compose.yml
tests/cases/manage_pgbouncer/docker-compose.yml
tests/cases/manage_pgpool2/docker-compose.yml
tests/cases/setup_barman/docker-compose.yml
tests/cases/setup_barmanserver/docker-compose.yml
tests/cases/setup_dbt2/docker-compose.yml
tests/cases/setup_dbt2_client/docker-compose.yml
tests/cases/setup_dbt2_driver/docker-compose.yml
tests/cases/setup_dbt3/docker-compose.yml
tests/cases/setup_dbt7/docker-compose.yml
tests/cases/setup_efm/docker-compose.yml
tests/cases/setup_hammerdb/docker-compose.yml
tests/cases/setup_hammerdbserver/docker-compose.yml
tests/cases/setup_pemagent/docker-compose.yml
tests/cases/setup_pemserver/docker-compose.yml
tests/cases/setup_pgbouncer/docker-compose.yml
tests/cases/setup_pgpool2/docker-compose.yml
tests/cases/setup_replication/docker-compose.yml
tests/cases/setup_repmgr/docker-compose.yml
tests/cases/setup_repo/docker-compose.yml
tests/tests/test_setup_repo.py

Use privileged:true in docker compose configuration.

Fix tests execution on Linux

---

roles/manage_pgbouncer/vars/EPAS_Debian.yml
roles/manage_pgbouncer/vars/EPAS_RedHat.yml
roles/setup_pgbouncer/vars/EPAS_Debian.yml
roles/setup_pgbouncer/vars/EPAS_RedHat.yml
tests/tests/conftest.py
tests/tests/test_setup_pgbouncer.py

And fix incorrect configuration file path.

Update edb-pgbouncer to 1.17

---

roles/init_dbserver/defaults/main.yml
roles/manage_dbpatches/defaults/main.yml
roles/manage_dbserver/defaults/main.yml
roles/setup_efm/defaults/main.yml
roles/setup_pemagent/defaults/main.yml
roles/setup_pemserver/defaults/main.yml
roles/setup_replication/defaults/main.yml
tests/cases/manage_dbpatches/playbook.yml
tests/cases/setup_efm/playbook.yml
tests/tests/test_manage_dbpatches.py
tests/tests/test_setup_efm.py

Adding support EFM 4.5

---

roles/setup_pemagent/defaults/main.yml
roles/setup_pemagent/tasks/pem_agent_config.yml

Exposing pem agent's batch script user variable

Exposing pem agent's batch script user variable

---

roles/autotuning/tasks/tune_pg_shared_buffers.yml
roles/autotuning/tasks/tune_postgres.yml
roles/autotuning/templates/tuned.conf.template

Updating Autotuning role based on the new release or Tuning Guide for Linux

Autotuning role update

---

roles/manage_pgbouncer/meta/main.yml
roles/manage_pgbouncer/tasks/main.yml
roles/manage_pgbouncer/tasks/manage_pgbouncer.yml
roles/manage_pgbouncer/tasks/pgbouncer_set_databases.yml
roles/manage_pgbouncer/tasks/pgbouncer_set_userlist.yml

Fixes linting issues in manage_pgbouncer role.

fix linting issues manage_pgbouncer

---

roles/setup_pgbackrest/meta/main.yml
roles/setup_pgbackrest/tasks/configure_pg_backup.yml
roles/setup_pgbackrest/tasks/configure_pg_settings.yml
roles/setup_pgbackrest/tasks/configure_pgbackrest.yml
roles/setup_pgbackrest/tasks/define_node_variables.yml
roles/setup_pgbackrest/tasks/exchange_ssh_keys.yml
roles/setup_pgbackrest/tasks/generate_ssh_keys.yml
roles/setup_pgbackrest/tasks/linux_update_etc_hosts.yml
roles/setup_pgbackrest/tasks/main.yml
roles/setup_pgbackrest/tasks/pgbackrest_install_PG.yml
roles/setup_pgbackrest/tasks/post_configure_pgbackrest.yml
roles/setup_pgbackrest/tasks/setup_pgbackrest.yml
roles/setup_pgbackrest/templates/pgbackrest_standby.async.conf.template
roles/setup_pgbackrest/templates/pgbackrest_standby.standard.conf.template

Fixes linting issues in setup_pgbackrest role. Tests have been successful for PG/EPAS 14/13 for rocky8, centos7, debian10 and ubuntu20.

fix linting issues for setup_pgbackrest role

---

roles/setup_barman/defaults/main.yml
roles/setup_barman/meta/main.yml
roles/setup_barman/tasks/configure_barman.yml
roles/setup_barman/tasks/configure_pg_backup.yml
roles/setup_barman/tasks/create_pg_user.yml
roles/setup_barman/tasks/exchange_ssh_keys.yml
roles/setup_barman/tasks/generate_pg_password.yml
roles/setup_barman/tasks/generate_ssh_keys.yml
roles/setup_barman/tasks/linux_update_etc_hosts.yml
roles/setup_barman/tasks/main.yml
roles/setup_barman/tasks/post_configure_barman.yml
roles/setup_barman/tasks/setup_barman.yml
roles/setup_barman/tasks/update_barman_pgpass.yml
roles/setup_barman/tasks/update_pg_hba.yml
roles/setup_barman/vars/EPAS_Debian.yml
roles/setup_barman/vars/EPAS_RedHat.yml
roles/setup_barman/vars/PG_Debian.yml
roles/setup_barman/vars/PG_RedHat.yml
roles/setup_barmanserver/defaults/main.yml
roles/setup_barmanserver/meta/main.yml
roles/setup_barmanserver/tasks/create_directories.yml
roles/setup_barmanserver/tasks/create_user.yml
roles/setup_barmanserver/tasks/generate_configuration.yml
roles/setup_barmanserver/tasks/generate_ssh_keys.yml
roles/setup_barmanserver/tasks/install_packages.yml
roles/setup_barmanserver/tasks/linux_update_etc_hosts.yml
roles/setup_barmanserver/tasks/main.yml
roles/setup_barmanserver/tasks/setup_barmanserver.yml

Fixes linting issues in both `setup_barman` role and `setup_barmanserver` role.

fix linting issues in barman roles

---

roles/manage_efm/README.md
roles/manage_efm/meta/main.yml
roles/setup_efm/README.md
roles/setup_efm/meta/main.yml
tests/cases/manage_efm/Makefile
tests/cases/manage_efm/docker-compose.yml
tests/cases/manage_efm/inventory.yml.j2
tests/cases/manage_efm/playbook.yml
tests/cases/manage_efm/vars.json
tests/config.yml
tests/tests/test_manage_efm.py
tests/tests/test_setup_efm.py
tests/tests/test_setup_efm_api.py

Builds manage_efm test cases and and updates setup_efm tests.

efm ubuntu

---

plugins/lookup/all_nodes.py
plugins/lookup/bdr_lead_master.py
plugins/lookup/bdr_nodes.py
plugins/lookup/efm_nodes.py
plugins/lookup/etcd_cluster_nodes.py
plugins/lookup/pg_sr_cluster_nodes.py
plugins/lookup/pgbackrest_nodes.py
plugins/lookup/pgpool2_nodes.py
plugins/lookup/supported_roles.py
roles/init_dbserver/vars/edb-ssl.yml
roles/install_dbserver/defaults/main.yml
roles/manage_dbpatches/defaults/main.yml
roles/manage_dbserver/vars/EPAS_Debian.yml
roles/manage_dbserver/vars/EPAS_RedHat.yml
roles/manage_efm/tasks/efm_db_password.yml
roles/setup_dbt3/tasks/dbt3_tpc.yml
roles/setup_dbt7/tasks/dbt7_tpc.yml
roles/setup_efm/defaults/main.yml
roles/setup_efm/tasks/efm_configure.yml
roles/setup_etcd/tasks/create_directories.yml
roles/setup_patroni/vars/edb-ssl.yml
tests/config.yml
tests/tests/conftest.py
tests/tests/test_setup_patroni.py

This commit fixes following linting issues Warnings :
F401 'ansible.errors.AnsibleError' imported but unused E303 too many blank lines (2)
E225 missing whitespace around operator
W391 blank line at end of file
E231 missing whitespace after ','
E129 visually indented line with same indent as next logical line And also improved test case for setup_patroni

Fixing linting issue and also improving setup_patroni test cases

---

roles/init_dbserver/templates/postgresql.conf.template
roles/install_dbserver/defaults/main.yml
roles/install_dbserver/tasks/main.yml
roles/manage_dbserver/tasks/manage_extensions.yml

Updates the pg_tuner package to include Debian OS's and updates all tasks associated with pg_tuner to include Debian.

Backport pg_tuner updates

---

plugins/lookup/pgpool2_nodes.py
roles/setup_barman/tasks/update_pg_hba.yml
roles/setup_pgpool2/tasks/pgpool2_setup_watchdog.yml

In `setup_barman` and `setup_pgpool2`, a jinja2 appending error was missed when updating to ansible-core 2.13. This fixes the error to allow the lists to be appended correctly. I have also double checked to make sure this issue is not found elsewhere.

Fix barman and pgpool2 append errors

---

roles/setup_barman/tasks/update_pg_hba.yml
roles/setup_pgpool2/tasks/pgpool2_setup_watchdog.yml

Backport commits to fix list appending errors.

Backport barman and pgpool updates

---

roles/setup_barman/tasks/setup_barman.yml

backporting commit 88ef28a from master

fix barman_no_configuration logic

---

roles/setup_efm/tasks/create_efm_user.yml

Adding extra privileges for efm user to reconfigure.num.sync parameter.

pg_read_all_stats and pg_reload_conf privileges for EFM user

---

roles/setup_replication/vars/EPAS_Debian.yml
roles/setup_replication/vars/PG_Debian.yml

Adding missing variables in setup_replication for force_initdb

Adding missing variables in setup_replication for force_initdb

---

roles/install_dbserver/tasks/install_dbserver.yml
roles/manage_dbpatches/tasks/manage_dbpatches.yml
roles/manage_efm/tasks/manage_efm.yml
roles/manage_pgpool2/tasks/manage_pgpool2.yml
roles/setup_barman/tasks/setup_barman.yml
roles/setup_barmanserver/tasks/setup_barmanserver.yml
roles/setup_efm/tasks/setup_efm.yml
roles/setup_patroni/tasks/setup_patroni.yml
roles/setup_pemagent/tasks/setup_pemagent.yml
roles/setup_pemserver/tasks/setup_pemserver.yml
roles/setup_pgpool2/tasks/setup_pgpool2.yml
roles/setup_replication/tasks/setup_replication.yml

Update roles to be compatible with EPAS 15

update for EPAS 15

---

roles/init_dbserver/tasks/rm_initdb.yml
roles/setup_efm/tasks/rm_efm_install_config.yml
roles/setup_replication/tasks/rm_replication.yml
roles/setup_replication/tasks/setup_replication.yml

Updates and enhances the `force_initdb`, `force_replication` and `force_efm` removal flag tasks. Uninstalls packages, removes configuration files, and reverts configuration settings.

Update force_initdb force_replication and force_efm

---

roles/manage_cnpg/defaults/main.yml

Removes duplicate lines in `manage_cnpg` defaults.

Review variable names

---

roles/manage_dbpatches/defaults/main.yml
roles/manage_dbpatches/tasks/efm_cluster_primary.yml
roles/setup_efm/tasks/validate_setup_efm.yml
tests/cases/manage_dbpatches/playbook.yml
tests/cases/manage_dbpatches/vars.json
tests/tests/test_manage_dbpatches.py

Adding support for EFM 4.6 in manage_dbserver

Adding support for EFM 4.6 in manage_dbserver

---

roles/setup_barman/vars/EPAS_Debian.yml
roles/setup_barman/vars/PG_Debian.yml
roles/setup_barman/vars/PG_RedHat.yml

Fixes the `pg_bin_path` variable within the respective `/vars/*` files.

fix pg_bin_path in setup_barman role

---

roles/setup_patroni/tasks/validate_setup_patroni.yml
tests/test-runner.py
tests/tests/test_setup_hammerdb.py

Add support for ansible-core 2.15. Minimal changes made but tested on all roles.

add ansible-core 2.15 support

---

roles/setup_dbt2/defaults/main.yml
roles/setup_dbt2/tasks/dbt2_install_packages_client.yml
roles/setup_dbt2/tasks/dbt2_install_packages_db.yml

* install rsync on client and database systems
* bump dbt2 version to v0.53.4

dbt2 playbook updates

---

roles/install_from_source/README.md
roles/install_from_source/defaults/main.yml
roles/install_from_source/tasks/main.yml

Install software from various sources:
* git
* tarball
* local directory
This provides basic functionality in its initial version.

install from source

---

roles/install_from_source/meta/main.yml

Adds the meta file for new role `install_from_source`.

add meta file for install_from_source

---

roles/setup_pgd/README.md

Updates the `setup_pgd` README. If more information is needed, please let me know.

update setup_pgd README

---

roles/install_dbserver/defaults/main.yml
roles/install_dbserver/tasks/linux_coredump.yml

* do not rewrite core_pattern
* fix install of debuginfo packages for epas

Update and fix core dump handling

---

roles/init_dbserver/templates/postgresql.conf.template
roles/install_dbserver/README.md

* update documentation for how to enable
* fix handling of edb_pg_tuner.autotune in the postgresql.conf template

EDB Postgres Tuner updates

---

roles/init_dbserver/README.md
roles/init_dbserver/defaults/main.yml
roles/init_dbserver/templates/postgresql.conf.template

* Enable more logging parameters for pgbadger
* Add install_auto_explain variable for enabling auto_explain shared library

Increase logging

---

roles/init_dbserver/templates/postgresql.conf.template
roles/install_dbserver/tasks/EPAS_Debian_install.yml
roles/install_dbserver/tasks/EPAS_RedHat_install.yml
roles/install_dbserver/tasks/PG_Debian_install.yml
roles/install_dbserver/tasks/PG_RedHat_install.yml

init_dbserver postgresql.conf.template load bdr shared library first

---

.github/workflows/push.yml
tests/test-runner.py

Fix `ansible-galaxy` bug while installing galaxy collections within `Dockerfile.ansible-tester`

update ansible-core version support with minor versions
