EnterpriseDB/edb-ansible

roles/init_dbserver/tasks/pg_set_superuser_password.yml

To prevent this kind of error when the hostname contains special chars that are not allowed in a slot name:
```
TASK [manage_dbserver : Check user defined parameters and update] ********************************************************************************************************************************************************************************************
failed: [primary-centos8.home.virt -> 192.168.122.33] (item={'name': 'primary_slot_name', 'value': 'primary-centos8'}) => {"ansible_loop_var": "line_item", "changed": false, "line_item": {"name": "primary_slot_name", "value": "primary-centos8"}, "msg": "Unable to get primary_slot_name value due to : invalid value for parameter \"primary_slot_name\": \"primary-centos8\"\n"}
```

Replace special chars in primary_slot_name by an underscore

---

playbook-examples/rhel_firewalld_rule.yml

Ansible `firewalld`module permits to load the new rule immediately, meaning that if used we don't have to reload `firewalld` manually to apply the new rules.

Load firewalld rules immediately

---

README.md
roles/manage_pgbouncer_databases/README.md
roles/manage_pgbouncer_databases/defaults/main.yml
roles/manage_pgbouncer_databases/tasks/main.yml
roles/manage_pgbouncer_databases/tasks/pgbouncer_set_databases.yml
roles/manage_pgbouncer_databases/templates/databases.ini.template
roles/manage_pgbouncer_users/README.md
roles/manage_pgbouncer_users/defaults/main.yml
roles/manage_pgbouncer_users/tasks/main.yml
roles/manage_pgbouncer_users/tasks/pgbouncer_set_userlist.yml
roles/manage_pgbouncer_users/templates/userlist.txt.template
roles/setup_pgbouncer/README.md
roles/setup_pgbouncer/defaults/main.yml
roles/setup_pgbouncer/tasks/main.yml
roles/setup_pgbouncer/tasks/pgbouncer_install.yml
roles/setup_pgbouncer/tasks/pgbouncer_setup.yml
roles/setup_pgbouncer/templates/pgbouncer.ini.template
roles/setup_pgbouncer/templates/pgbouncer.unit.conf.template

This commit introduces PgBouncer support by bringing 3 new roles:
* setup_pgbouncer: this role is in charge of installing and
configuring PgBouncer.
* manage_pgbouncer_users: manage PgBouncer user list.
* manage_pgbouncer_databases: manage PgBouncer pool connection
list.

PgBouncer support

---

roles/setup_replication/tasks/primary_synchronous_param.yml

To allow special char usage in standby name.

Add double quotes to synchronous standby name

---

roles/setup_pem/vars/EPAS.yml
roles/setup_pem/vars/PG.yml

To avoid this kind of error when the `setup_pem` role is executed alone: `The task includes an option with an undefined variable. The error was: 'pg_data' is undefined`

Define pg_data in setup_pem

---

roles/init_dbserver/tasks/main.yml
roles/install_dbserver/defaults/main.yml
roles/install_dbserver/tasks/main.yml
roles/manage_dbserver/defaults/main.yml
roles/manage_dbserver/tasks/main.yml
roles/manage_pgbouncer_databases/defaults/main.yml
roles/manage_pgbouncer_databases/tasks/main.yml
roles/manage_pgbouncer_users/defaults/main.yml
roles/manage_pgbouncer_users/tasks/main.yml
roles/setup_efm/defaults/main.yml
roles/setup_efm/tasks/main.yml
roles/setup_pem/defaults/main.yml
roles/setup_pem/tasks/main.yml
roles/setup_pgbouncer/defaults/main.yml
roles/setup_pgbouncer/tasks/main.yml
roles/setup_replication/defaults/main.yml
roles/setup_replication/tasks/main.yml
roles/setup_repo/tasks/main.yml

With this commit, each role is able to define its own list of
supported node types.

Add the supported_node_type variable

---

README.md
roles/manage_pgpool2/README.md
roles/manage_pgpool2/defaults/main.yml
roles/manage_pgpool2/meta/main.yml
roles/manage_pgpool2/tasks/main.yml
roles/manage_pgpool2/tasks/pgpool2_manage_configuration.yml
roles/manage_pgpool2/tasks/pgpool2_manage_users.yml
roles/manage_pgpool2/vars/EPAS.yml
roles/manage_pgpool2/vars/PG.yml
roles/setup_pgpool2/README.md
roles/setup_pgpool2/defaults/main.yml
roles/setup_pgpool2/meta/main.yml
roles/setup_pgpool2/tasks/main.yml
roles/setup_pgpool2/tasks/pgpool2_configure_backend_pg_hba.yml
roles/setup_pgpool2/tasks/pgpool2_configure_backends.yml
roles/setup_pgpool2/tasks/pgpool2_configure_loadbalancing.yml
roles/setup_pgpool2/tasks/pgpool2_install.yml
roles/setup_pgpool2/tasks/pgpool2_setup.yml
roles/setup_pgpool2/tasks/pgpool2_setup_sr_mode.yml
roles/setup_pgpool2/tasks/pgpool2_setup_ssl.yml
roles/setup_pgpool2/tasks/pgpool2_setup_user_auth.yml
roles/setup_pgpool2/tasks/pgpool2_setup_watchdog.yml
roles/setup_pgpool2/templates/pgpool-II.unit.conf.template
roles/setup_pgpool2/templates/pgpool.sudoers.d.conf.template
roles/setup_pgpool2/vars/EPAS.yml
roles/setup_pgpool2/vars/PG.yml

This PR introduces PgpoolII deployment and management.
PgpoolII features availables:
- Read only queries load balancing.
- PgpoolII instances High-Availability with VIP management.
- Automated write queries routing to right Postgres node, even after Postgres failover.
- SSL support.
Battle tested on:
- CentOS 8 / PostgreSQL 13 / PgpoolII 4.1 (community)
- CentOS 7 / EPAS 12 / EDB PgpoolII 4.1

PgpoolII support

---

roles/setup_replication/tasks/setup_replication.yml

This is only needed for replication slot names, we don't have to do
it for the application_name.

Do not replace special chars in sync standby names

---

Makefile
galaxy.template.yml

Fixes #91 
This Makefile helps to build and publish the Ansible collection on
the Galaxy platform.
Build the collection:
make EDB_ANSIBLE_VERSION=x.y.z build
Publish the collection once it has been built:
make EDB_ANSIBLE_VERSION=x.y.z API_KEY=xxxxxxxx publish
Note: the API key can be found at https://galaxy.ansible.com/me/preferences
Clean up the generated files:
make EDB_ANSIBLE_VERSION=x.y.z clean

Add Makefile for publishing in Galaxy

---

README.md
inventory.yml
lookup_plugins/barman_server.py
playbook.yml
roles/setup_barman/README.md
roles/setup_barman/defaults/main.yml
roles/setup_barman/tasks/configure_barman.yml
roles/setup_barman/tasks/configure_pg_backup.yml
roles/setup_barman/tasks/create_pg_user.yml
roles/setup_barman/tasks/exchange_ssh_keys.yml
roles/setup_barman/tasks/generate_pg_password.yml
roles/setup_barman/tasks/generate_ssh_keys.yml
roles/setup_barman/tasks/main.yml
roles/setup_barman/tasks/setup_barman.yml
roles/setup_barman/tasks/update_barman_pgpass.yml
roles/setup_barman/tasks/update_pg_hba.yml
roles/setup_barman/templates/barman.postgres.template
roles/setup_barman/templates/barman.rsync.template
roles/setup_barmanserver/README.md
roles/setup_barmanserver/defaults/main.yml
roles/setup_barmanserver/tasks/create_directories.yml
roles/setup_barmanserver/tasks/create_user.yml
roles/setup_barmanserver/tasks/generate_configuration.yml
roles/setup_barmanserver/tasks/generate_ssh_keys.yml
roles/setup_barmanserver/tasks/install_packages.yml
roles/setup_barmanserver/tasks/main.yml
roles/setup_barmanserver/tasks/setup_barmanserver.yml
roles/setup_barmanserver/templates/barman.conf.template
vars_plugins/host_supported_roles.py

This PR includes:
- new role for Barman server deployment: `setup_barmanserver`
- new role for configuring Barman on Postgres nodes: `setup_barman`
Local backups are not supported.
Remote backup methods supported are `postgres` and `rsync`.

Barman support

---

roles/autotuning/templates/tuned.conf.template

Overcommit & swapiness tuning should only be applied on dedicated
Postgres nodes.

Do not tune overcommit and swapiness on pemserver

---

roles/manage_dbserver/tasks/generate_password.yml
roles/setup_barman/tasks/generate_pg_password.yml

Because input_password cannot be reset, we must pass it with an empty
value if we want the password file being created.

Pass input_password to generate_password

---

roles/manage_dbserver/tasks/manage_db.yml

I tried to utilize the manage_dbserver role as follows in order to deploy a database:
pg_databases:
- name: dbnew
owner: postgres
encoding: UTF-8
Ansible failed with the following traceback:
The full traceback is:
Traceback (most recent call last):
File "/tmp/ansible_postgresql_db_payload_8uxzwrrs/ansible_postgresql_db_payload.zip/ansible/modules/database/postgresql/postgresql_db.py", line 581, in main
File "/tmp/ansible_postgresql_db_payload_8uxzwrrs/ansible_postgresql_db_payload.zip/ansible/modules/database/postgresql/postgresql_db.py", line 268, in db_create
File "/tmp/ansible_postgresql_db_payload_8uxzwrrs/ansible_postgresql_db_payload.zip/ansible/module_utils/database.py", line 126, in pg_quote_identifier
raise SQLParseError('PostgreSQL does not support %s with more than %i dots' % …

Adapted db template reference to allow for value substituion

---

roles/setup_barman/tasks/exchange_ssh_keys.yml

Dear EDB team!
Please review my pull request to preserve the ownership of the known_hosts files for the users postgres and barman when using the role setup_barman. Up to now, the ownership seems to get lost and will be root. This behaviour might be connected to Ticket [Ansible ticket #69231](https://github.com/ansible/ansible/pull/69231). I added to the Ansible tasks the parameter 'becoming_user' with the variables for either postgres or barman user.
Best regards,
Dirk

Preserve ownership of known_hosts file by becoming postgres/barman user.

---

roles/setup_efm/templates/pcp_attach_all.sh.template
roles/setup_efm/templates/pg_pcp_health.sh.template
roles/setup_pgpool2/tasks/pgpool2_setup_sr_mode.yml

Due to missing PGDATABASE environment variablein the pcp_attach_all.sh and pg_pcp_health.sh scipts, pcp commands are logging the following message in postgres log:
efm@efm app=[unknown] FATAL:  no pg_hba.conf entry for host 'xxx.xxx.xxxx.xxx', user 'efm', database 'efm', SSL on 
This commit fixes that. 
Pgpool2 sr_user has missing permission. Added pg_monitor role to pgpool2 user

Fixes for efm pgpool integration and pgpool2 permissions

---

plugins/lookup/pg_sr_cluster_nodes.py

Handle the case when the current node is not part of any SR cluster
found.

Fixes pg_sr_cluster_nodes lookup filter

---

roles/install_dbserver/tasks/PG_RedHat_install.yml

Ansible combining the comment and command in shell module due to which in built postgresql module is not getting disabled. This commit fixes that

CentOS8/RHEL8 disable inbuilt PG module

---

plugins/lookup/pgpool2_nodes.py

Return an empty list even if there isn't any pgpool2 node defined
in the inventory.

Fix pgpool2_nodes lookup filter

---

meta/runtime.yml

To avoid the following warning on 2.11+:
```
[WARNING]: Collection edb_devops.edb_postgres does not support Ansible version
```

Update requires_ansible to ">=2.10"

---

roles/setup_pemagent/tasks/pem_agent_hba.yml

As a fallback method to avoid failure due to random SSL error when
registering PEM agents.

Allow host connections to PEM instance

---

roles/init_dbserver/defaults/main.yml
roles/init_dbserver/tasks/pg_set_superuser_password.yml
roles/setup_replication/defaults/main.yml
roles/setup_replication/tasks/pg_basebackup.yml
roles/setup_replication/tasks/upstream_node_slots.yml

Hi,
It's not always convenient to use replication slots when you already have archive/restore_command configured and using a dedicated backup tool (barman, pgbackrest,...).
Adding a `use_replication_slots` (default true, so no behavior change to be expected) option seems a fair and quick way to achieve this, for at least `init_dbserver` and `setup_replication` roles.
Thanks in advance for your review.
Kind Regards,
Stefan

Allow to install and setup replication without using replication slots

---

roles/manage_dbserver/vars/EPAS_Debian.yml
roles/manage_dbserver/vars/EPAS_RedHat.yml
roles/manage_dbserver/vars/PG_Debian.yml
roles/manage_dbserver/vars/PG_RedHat.yml
roles/setup_replication/tasks/rm_replication.yml

This fix some path issues for debian in `setup_replication` and `manage_dbserver`.
It also cleans up some multi-instance support left-overs.

Debian fix setup_replication and manage_dbserver

---

roles/install_dbserver/tasks/EPAS_RedHat_rm_install.yml

EPAS_RedHat_rm_install has an issue. For uninstallation/removing of package in ansible 'state:absent' instead of 'state:present'

Fixed uninstallation issue

---

roles/setup_barman/tasks/post_configure_barman.yml
roles/setup_barman/tasks/update_barman_pgpass.yml

Do not execute the backup and check commands on standbys. Standby
nodes must be configured and ready to be backuped in case of
switchover/failover but are not supposed to be backuped when they
still are in recovery mode.
Use throttle=1 when updating the .pgpass file on the barman server
to avoid race condition that can lead to missing entries when working
with multiple PG nodes.

Barman fixes

---

roles/init_dbserver/defaults/main.yml
roles/init_dbserver/vars/EPAS_Debian.yml
roles/init_dbserver/vars/EPAS_RedHat.yml
roles/init_dbserver/vars/PG_Debian.yml
roles/init_dbserver/vars/PG_RedHat.yml
roles/manage_dbserver/defaults/main.yml
roles/setup_efm/defaults/main.yml
roles/setup_replication/defaults/main.yml
roles/setup_replication/vars/EPAS_Debian.yml
roles/setup_replication/vars/EPAS_RedHat.yml
roles/setup_replication/vars/PG_Debian.yml
roles/setup_replication/vars/PG_RedHat.yml

From `edb-<cluster-name>-<efm-version>` to `edb-efm-<cluster-name>-<efm-version>`.
By default, the service name was: `edb-main-4.2`, which is not meaningful

Update EFM service name

---

roles/setup_repo/tasks/PG_RedHat_setuprepos.yml

Executing this command makes the import of GPG keys effective for
all the following dnf/yum executions.
If we don't do that, import of the keys will be done later by
another dnf/yum command. This shouldn't be an issue, but for unknown
reason, when dnf/yum imports keys then it does only that, whatever
the command being executed.
More details here:
https://bugzilla.redhat.com/show_bug.cgi?id=1768206

Execute yum updateinfo -y

---

plugins/lookup/pg_service.py

To cover the case where the variables a not defined by users and
are only defined in defaults/main.yml which makes them not
available in the lookup function.

Use default values in the pg_service lookup func.

---

roles/setup_repo/tasks/PG_RedHat_setuprepos.yml

Due to old version of this package, the installation of some of
the repositories could fail with the following error:
Failure downloading https://[...].rpm, Request failed: <urlopen
error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed
(_ssl.c:618)>
Issue reported by Stefan Fercot (@pgstef)

Force the update of ca-certificates

---

roles/manage_dbserver/tasks/manage_hba_conf.yml

Use throttle=1 when updating the pg_hba.conf file

---

plugins/lookup/repmgr_nodes.py
plugins/lookup/supported_roles.py
roles/setup_repmgr/README.md
roles/setup_repmgr/defaults/main.yml
roles/setup_repmgr/tasks/exchange_ssh_keys.yml
roles/setup_repmgr/tasks/generate_ssh_keys.yml
roles/setup_repmgr/tasks/linux_update_etc_hosts.yml
roles/setup_repmgr/tasks/main.yml
roles/setup_repmgr/tasks/repmgr_configure.yml
roles/setup_repmgr/tasks/repmgr_configure_spl.yml
roles/setup_repmgr/tasks/repmgr_hba.yml
roles/setup_repmgr/tasks/repmgr_install.yml
roles/setup_repmgr/tasks/repmgr_prepare_hba.yml
roles/setup_repmgr/tasks/repmgr_register_node.yml
roles/setup_repmgr/tasks/repmgr_setup_db.yml
roles/setup_repmgr/tasks/repmgr_setup_db_user.yml
roles/setup_repmgr/tasks/repmgr_setup_systemd.yml
roles/setup_repmgr/tasks/repmgr_sudoers.yml
roles/setup_repmgr/tasks/repmgr_update_pgpass.yml
roles/setup_repmgr/tasks/setup_repmgr.yml
roles/setup_repmgr/templates/default.repmgrd.j2
roles/setup_repmgr/templates/override.conf.j2
roles/setup_repmgr/templates/repmgr.conf.j2
roles/setup_repmgr/templates/sudoers.d.repmgr.conf.j2
roles/setup_repmgr/vars/PG_Debian.yml
roles/setup_repmgr/vars/PG_RedHat.yml

This commit introduces repmgr deployment support.
Automatic failover and repmgrd daemon setup are enabled by
default.
The following architectures are supported:
- 1 primary node, N standby nodes
- 1 primary node, N standby nodes, M witness nodes
Only PostgreSQL on CentOS/Redhat 8 and Debian 10 are supported so
far. Repmgr packages for EPAS on CentOS/Redhat are currently broken,
EPAS support will be added once the packages are fixed.
pgpool2 and barman integration will be implemented later.

Repmgr support - part 1

---

roles/setup_dbt2/tasks/install_packages_client.yml
roles/setup_dbt2/tasks/install_packages_db.yml

Reflecting recent packaging changes such that C and pl/pgsql stored
functions have been separated.
The database node only needs to have the C stored functions.  While it
is possible to use the pl/pgsql stored functions, these playbooks are
currently designed to simplify options and use recommended
configurations.
The client node will now always install the data generator and pl/pgsql
stored functions in the event that it is used against a DBaaS option.

Update dbt2 packages to install

---

roles/manage_dbserver/tasks/copy_files.yml

Fixing the following error:
```
template error while templating string: expected token ',', got 'integer'. String: {{ line_item.mode | default(0644) }}
```

pg_copy_files: default mode value must be a string

---

roles/init_dbserver/tasks/pg_setup_systemd.yml

This bug has been found on RockyLinux 8.4/8.5 with systemd 239.
Working around this issue consist in executing systemctl
daemon-reload right after the systemctl stop command.

Prevent Postgres service hanging when stopping it

---

.github/workflows/push.yml
README.md
roles/setup_repo/defaults/main.yml
roles/setup_repo/tasks/PG_RedHat_setuprepos.yml
roles/setup_repo/tasks/setup_repo.yml
tests/Makefile.mk
tests/cases/init_dbserver/docker-compose.yml
tests/cases/install_dbserver/docker-compose.yml
tests/cases/manage_dbserver/docker-compose.yml
tests/cases/setup_replication/docker-compose.yml
tests/cases/setup_repo/docker-compose.yml
tests/docker/exec-tests.sh
tests/scripts/build-inventory.py
tests/test-runner.py
tests/tests/conftest.py
tests/tests/test_setup_repo.py

When the variable enable_edb_repo is set to false.
This commit adds new github actions executing the test we currently
have on every git push. This is now possible because using EDB
credentials is not required anymore when deploying software coming
from the community package repository.

Don't configure access to EDB package repo.

---

roles/init_dbserver/defaults/main.yml
roles/init_dbserver/tasks/create_directories.yml
roles/init_dbserver/tasks/pg_initdb.yml
roles/init_dbserver/tasks/rm_initdb.yml
roles/init_dbserver/templates/postgresql.conf.template
roles/setup_efm/defaults/main.yml
roles/setup_efm/tasks/rm_efm_install_config.yml
roles/setup_pemagent/defaults/main.yml
roles/setup_pemserver/defaults/main.yml
roles/setup_replication/defaults/main.yml
roles/setup_replication/tasks/create_directories.yml

This PR allows users to use edb_audit_directory as a parameter and can be declared in a playbook.

Adding edb_audit_directory as a parameter

---

tests/tests/test_setup_repo.py

yum repolist no longer lists "PostgreSQL common RPMs for RHEL/CentOS" and instead lists "PostgreSQL common RPMs for RHEL / Rocky 8"

setup_repo testing framework update

---

roles/init_dbserver/tasks/init_dbserver.yml
roles/setup_barman/tasks/configure_barman.yml
roles/setup_barman/tasks/configure_pg_backup.yml
roles/setup_barman/tasks/exchange_ssh_keys.yml
roles/setup_barman/tasks/post_configure_barman.yml
roles/setup_barman/tasks/setup_barman.yml
roles/setup_barman/tasks/update_barman_pgpass.yml
roles/setup_barmanserver/tasks/setup_barmanserver.yml
roles/setup_efm/tasks/efm_configure.yml
roles/setup_efm/tasks/efm_pgpool2_integration.yml
roles/setup_efm/tasks/setup_efm.yml
roles/setup_pemagent/tasks/setup_pemagent.yml
roles/setup_pemserver/tasks/setup_pemserver.yml
roles/setup_pgpool2/tasks/setup_pgpool2.yml
roles/setup_replication/tasks/pg_basebackup.yml
roles/setup_replication/tasks/setup_replication.yml
roles/setup_replication/tasks/upstream_node.yml
roles/setup_replication/vars/EPAS_Debian.yml
roles/setup_replication/vars/EPAS_RedHat.yml
roles/setup_replication/vars/PG_Debian.yml
roles/setup_replication/vars/PG_RedHat.yml
roles/setup_repmgr/tasks/exchange_ssh_keys.yml
roles/setup_repmgr/tasks/setup_repmgr.yml
roles/setup_repmgr/templates/repmgr.conf.j2

This is usually not necessary when use_hostname is defined in the
playbook file itself, or in an external json file. But, when
passing this boolean variable through the command line with:
-e 'use_hostname=false', in this case, the value is considered as
a string, then all the conditions based only on the value are true.
This fix may help in #306

Cast use_hostname to bool

---

plugins/lookup/all_nodes.py

Ignore hosts that are part to Ansible groups not related to this
collection.

Fix the all_nodes lookup function

---

tests/cases/setup_hammerdb/Makefile
tests/cases/setup_hammerdb/docker-compose.yml
tests/cases/setup_hammerdb/inventory.yml.j2
tests/cases/setup_hammerdb/playbook.yml
tests/cases/setup_hammerdb/vars.json
tests/config.yml
tests/tests/test_setup_hammerdb.py

- load-tproc-c is installed in the correct path
- run-tproc-c is installed in the correct path
- max_connections matches the default max_connections
- max_wal_size matches the default max_wal_size 
Cannot be included in Github Action Workflow because setup_hammerdb (tshirt_size = small) assumes it has at least 32 GB of free memory. The default for docker is 8 GB.

Setup_hammerdb testing framework

---

roles/install_dbserver/defaults/main.yml
roles/install_dbserver/tasks/EPAS_Debian_install.yml
roles/install_dbserver/tasks/EPAS_Debian_rm_install.yml
roles/install_dbserver/tasks/EPAS_RedHat_install.yml
roles/install_dbserver/tasks/EPAS_RedHat_rm_install.yml
roles/install_dbserver/tasks/PG_Debian_install.yml
roles/install_dbserver/tasks/PG_Debian_rm_install.yml
roles/install_dbserver/tasks/PG_RedHat_install.yml
roles/install_dbserver/tasks/PG_RedHat_rm_install.yml

This allows trying early releases of PG/EPAS when sslutils packages aren't available yet.

Only install sslutils packages when pg_ssl is enabled

---

roles/install_dbserver/tasks/EPAS_RedHat_install.yml
roles/install_dbserver/tasks/EPAS_RedHat_rm_install.yml
roles/install_dbserver/tasks/PG_RedHat_install.yml
roles/install_dbserver/tasks/PG_RedHat_rm_install.yml
tests/tests/test_install_dbserver.py

On RedHat family in version 7, the new package name of the Postgres
driver for Python is python2-psycopg2. Even if packages named with
the original name (python-psycopg2) are still available, they
shouldn't be installed because of conflicts with packages depending
on python2-psycopg2.

Avoid package conflict with python2-psycopg2

---

roles/setup_barman/README.md
roles/setup_barman/tasks/configure_barman.yml
roles/setup_barman/tasks/exchange_ssh_keys.yml
roles/setup_barman/tasks/post_configure_barman.yml
roles/setup_barman/tasks/setup_barman.yml
roles/setup_barman/tasks/update_barman_pgpass.yml
roles/setup_barman/templates/barman.postgres.template

In the High-Availability context, when using a Virtual IP address for
routing read/write traffic to the primary node, then it's possible
to configure barman to use this VIP address as Postgres connection
endpoint. This way, in case of timeline change (following a
failover or switchover event), barman will be able to automatically
fetch new WAL records coming from the new primary node, without
requiring any manual operation.
This configuration is only possible when using the `postgres` backup
method, which is based on backup and WAL archiving using streaming
replication.
New hostvars:
- barman_private_vip: VIP address of the primary node. This VIP
must be already active on the primary before configuring barman.
- barman_no_configuration: Disable the creation of barman
configuration and …

Allow VIP usage with Barman

---

roles/setup_dbt2/tasks/dbt2_install_packages_client.yml
roles/setup_dbt2/tasks/dbt2_install_packages_db.yml
roles/setup_dbt2/tasks/dbt2_install_packages_driver.yml
roles/setup_dbt3/tasks/dbt3_install_packages.yml
roles/setup_dbt7/tasks/dbt7_install_packages.yml

os wasn't being set in these playbooks.  Just use ansible_os_family.  We
can check the major version when we actually support more than one major
version in these playbooks.

Fix os checking in DBT-* playbooks

---

roles/manage_dbserver/tasks/manage_postgres_params.yml

Executing the role "autotuning" comes at the cost of restarting the postgres server no matter if it is needed.
This is due to the fact, that the task "Register the restart requirements" traverses all params and if one of them has restart_required attached to it, the fact "params_restart_required" is set to true.
If I execute the role "autotuning" it will include "autovacuum_max_workers".
This has "restart_required" attached to it.
However it also has "changed" set to false.
ok: [primary1] => (item={'name': 'autovacuum_max_workers', 'restart_required': True, 'prev_val_pretty': '5', 'value_pretty': '5', 'context': 'postmaster', 'changed': False, 'invocation': {'module_args': {'login_unix_socket': '/var/run/postgresql', 'port': 5432, 'db': 'postgres', 'login_user': 'postgres', 'name': …

adapt restart condition in manage_postgres_params 

---

README.md
playbook-examples/pem_server_primary_two_standbys/playbook.yml
playbook-examples/primary_two_standbys_with_efm/playbook.yml
playbook.yml
roles/setup_repo/README.md
roles/setup_repo/defaults/main.yml
roles/setup_repo/tasks/PG_Debian_setuprepos.yml
roles/setup_repo/tasks/PG_RedHat_rm_repos.yml
roles/setup_repo/tasks/PG_RedHat_setuprepos.yml
roles/setup_repo/tasks/setup_repo.yml

This PR adds the support of EDB Repos 2.0.
Details of EDB Repos 2.0 is given below:
```
* Currently available for EDB Enterprise and EDB Standard
* Token-based authentication
* Single, simple URL for all download types
* Currently supporting Red Hat Enterprise Linux (RHEL), Oracle Linux (OL), CentOS, Rocky Linux, AlmaLinux, Debian, Ubuntu, and SUSE Linux Enterprise Server (SLES)
```

Adding support for EDB Repos 2.0 in setup_repo role

---

roles/setup_pgpool2/tasks/pgpool2_install.yml

On the os' from the redhat family in version 8, the default
postgresql meta package must be disabled if we to install packages
depending on the postgresql-X-server packages and coming from EDB
or PGDG repo.
Error was:
Problem: package pgpool-II-pcp-4.3.2-1.rhel8.x86_64 requires
postgresql14-server, but none of the providers can be installed
Reported by: Sergio Romera

pgpool2: disable builtin postgresql package

---

roles/setup_barman/tasks/configure_barman.yml
roles/setup_barman/tasks/exchange_ssh_keys.yml
roles/setup_barman/tasks/post_configure_barman.yml
roles/setup_barman/tasks/update_barman_pgpass.yml
roles/setup_efm/tasks/setup_efm.yml
roles/setup_pemagent/tasks/pem_agent_hba.yml
roles/setup_pemagent/tasks/pem_agent_register_db_remote.yml
roles/setup_pemagent/tasks/setup_pemagent.yml
roles/setup_pgpool2/tasks/pgpool2_create_db_user.yml
roles/setup_pgpool2/tasks/pgpool2_setup_sr_mode.yml
roles/setup_pgpool2/tasks/setup_pgpool2.yml
roles/setup_replication/tasks/setup_replication.yml
roles/setup_replication/tasks/upstream_node.yml
roles/setup_repmgr/tasks/exchange_ssh_keys.yml

Using ansible_host with delegate_to works only when using the SSH
connector and the default SSH port (22).
Using inventory_hostname is more portable and allows different SSH
port without needing additional SSH configuration.

Use inventory_hostname with delegate_to

---

roles/manage_dbpatches/defaults/main.yml
roles/manage_dbpatches/tasks/apply_db_patches_one_node.yml
roles/manage_dbpatches/tasks/apply_primary_patches.yml
roles/manage_dbpatches/tasks/manage_dbpatches.yml
roles/manage_dbpatches/tasks/update_standby_sequential.yml

Adding checks for synchronization of old primary before switchover. This PR also add capabilities where user can choose if they want to apply patches to only primary or standbys.

Synchronization check in manage_dbpatches

---

tests/scripts/lib/docker.py

This argument was added in python37, we want to support python36.

Don't use capture_output with subprocess.run()

---

roles/install_dbserver/defaults/main.yml
roles/install_dbserver/tasks/EPAS_Debian_install.yml
roles/install_dbserver/tasks/EPAS_RedHat_install.yml
roles/install_dbserver/tasks/PG_Debian_install.yml
roles/install_dbserver/tasks/PG_RedHat_install.yml
roles/setup_repo/defaults/main.yml
roles/setup_repo/tasks/PG_Debian_setuprepos.yml
roles/setup_repo/tasks/PG_RedHat_setuprepos.yml

Removing the bdr nodes checks for setup_repo. Now the installation of BDR packages and setup_repo are based on install_bdr_packages and tpa_subscription_token

Remove setup_repo for BDR dependencies on BDR nodes. 

---

roles/setup_replication/tasks/setup_replication.yml

Fixing the failure occurs if you don't have only asynchronous standby properties set in the inventory file

Asynchronous standby fix for setup_replication

---

README.md
roles/autotuning/defaults/main.yml
roles/autotuning/tasks/setup_tuned.yml
roles/init_dbserver/defaults/main.yml
roles/init_dbserver/tasks/pg_setup_systemd.yml
roles/install_dbserver/defaults/main.yml
roles/install_dbserver/tasks/EPAS_RedHat_install.yml
roles/install_dbserver/tasks/EPAS_RedHat_rm_install.yml
roles/install_dbserver/tasks/PG_RedHat_install.yml
roles/install_dbserver/tasks/PG_RedHat_rm_install.yml
roles/manage_pgbouncer/defaults/main.yml
roles/manage_pgpool2/defaults/main.yml
roles/setup_barman/defaults/main.yml
roles/setup_barmanserver/defaults/main.yml
roles/setup_barmanserver/tasks/install_packages.yml
roles/setup_dbt2/defaults/main.yml
roles/setup_dbt2_driver/defaults/main.yml
roles/setup_efm/defaults/main.yml
roles/setup_pemagent/defaults/main.yml
roles/setup_pemserver/defaults/main.yml
roles/setup_pgbouncer/defaults/main.yml
roles/setup_pgpool2/defaults/main.yml
roles/setup_pgpool2/tasks/pgpool2_install.yml
roles/setup_replication/defaults/main.yml
roles/setup_repmgr/defaults/main.yml
roles/setup_repo/defaults/main.yml
roles/setup_repo/tasks/PG_RedHat_setuprepos.yml

This commit adds OracleLinux7 support and revisits how the OS family detection is performed. In the future, adding support to other OS' from the RedHat family will be easier.

OracleLinux7 support

---

roles/manage_dbpatches/defaults/main.yml
roles/setup_efm/tasks/efm_configure.yml

Added declaration of variables of efm_eager_failover in manage_dbpatches. Also, protected properties_changes from causing any failure due to no changes.

Minor fixes of EFM eager failover

---

roles/setup_efm/tasks/setup_efm.yml

Fixing a Permission denied error when the ssh_user does not have sufficient rights on PGDATA.

setup_efm: execute WAL checking op. with root priv

---

roles/setup_repo/tasks/PG_Debian_setuprepos.yml

Hello,
Repository setup fails on Debian because auth_conf is not set when enable_edb_repo is false, playbook terminates with the following error message :
`FAILED! => {"msg": "The conditional check 'not auth_conf.stat.exists or auth_conf.stat.size == 0' failed. The error was: error while evaluating conditional (not auth_conf.stat.exists or auth_conf.stat.size == 0): 'dict object' has no attribute 'stat'\n\nThe error appears to be in '.ansible/collections/ansible_collections/edb_devops/edb_postgres/roles/setup_repo/tasks/PG_Debian_setuprepos.yml': line 10, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Build EDB auth conf\n  ^ here\n"}`

Fix PG repo setup on Debian

---

roles/setup_efm/defaults/main.yml
roles/setup_efm/tasks/efm_api_node_state_setup.yml
roles/setup_efm/tasks/setup_efm.yml
roles/setup_efm/templates/efm-api-node-state-config.toml.template
tests/cases/setup_efm_api/Makefile
tests/cases/setup_efm_api/docker-compose.yml
tests/cases/setup_efm_api/inventory.yml.j2
tests/cases/setup_efm_api/playbook.yml
tests/cases/setup_efm_api/vars.json
tests/config.yml
tests/tests/test_setup_efm_api.py

This commit adds support to the EFM api component on EL7.
For enabling it, the efm_api_node_state var must be set to true.

efm-api-node-state support

---

roles/setup_barman/README.md

Removes the limitation around using `backup_method = rsync` against standby nodes. It is now possible to backup standby nodes using `backup_method = rsync` with all currently supported PostgreSQL versions so the limitation no longer applies. This is true as long as `backup_options = concurrent_backup` which is the case in edb-ansible for both rsync and postgres backup methods.
Closes #397.

Remove standby limitation from setup_barman README.md

---

roles/setup_barman/defaults/main.yml
roles/setup_barmanserver/defaults/main.yml
roles/setup_barmanserver/tasks/install_packages.yml
tests/cases/setup_barman/Makefile
tests/cases/setup_barman/docker-compose.yml
tests/cases/setup_barmanserver/Makefile
tests/cases/setup_barmanserver/docker-compose.yml
tests/config.yml
tests/test-runner.py

Passed tests with PG 12, 13, and 14 and EPAS 14. EPAS 12 and 13 are returning an error in the `init_dbserver` role so I skipped them for now.

Add ubuntu support to barman roles

---

roles/install_dbserver/tasks/EPAS_Debian_install.yml

Adds the commands to drop default database before the variable `install_package` is called again.

fix epas < 14 install

---

roles/setup_dbt2/defaults/main.yml
roles/setup_dbt2/tasks/dbt2_install_packages_driver.yml
roles/setup_dbt2_client/defaults/main.yml
roles/setup_dbt2_driver/defaults/main.yml

Bump the dbt2 version to [v0.48.4](https://github.com/osdldbt/dbt2/blob/v0.48.4/ChangeLog), which contains fixes for capturing postgresql database statistics from DBaaS systems.
The DBT2 driver system also needs to have psql installed.

dbt2 related udpates

---

roles/setup_pemagent/defaults/main.yml
roles/setup_pemagent/tasks/pem_agent_install.yml
roles/setup_pemagent/tasks/setup_pemagent.yml

This commit allows users to configure pemagent in case the user doesn't have access to ssh to the PEM server. To make it possible, we have added the following options:
1. node_ssh_to_pemserver: true
2. enable_pemagent_barman: true

Allow pemagent only configuration

---

.github/workflows/push.yml

Update workflow tests in `push.yml` to include the `ANSIBLE_CORE_VERSION` environment variable. If it is not set, the test will be unable to build the `ansible-tester` docker image and it will fail.

update workflow tests

---

roles/setup_hammerdb/defaults/main.yml
roles/setup_hammerdb/tasks/install_tproc-c_load_scripts.yml
roles/setup_hammerdb/tasks/main.yml
roles/setup_hammerdbserver/defaults/main.yml
roles/setup_hammerdbserver/tasks/main.yml
tests/cases/setup_hammerdb/Makefile
tests/cases/setup_hammerdb/docker-compose.yml
tests/cases/setup_hammerdbserver/Makefile
tests/cases/setup_hammerdbserver/docker-compose.yml
tests/config.yml

Changes version of hammerdb to v4.6.
Removes touchstone tasks from both hammerdb roles. 
Adds support for Debian10 and Ubuntu20 for both hammerdb roles.

Hammerdb update

---

.ansible-lint

Example of a new error we can ignore:
```
args[module]: value of contype must be one of: local, host, hostssl, hostnossl, hostgssenc, hostnogssenc, got: {{ line_item.contype | default('hostssl') }}
roles/manage_dbserver/tasks/manage_hba_conf.yml:15 Task/Handler: Manage ip address entries into pg_hba file
```

ansible-lint: ignore new checks

---

plugins/modules/README.md
plugins/modules/linesinfile.py
roles/init_dbserver/tasks/linux_update_etc_hosts.yml
roles/init_dbserver/tasks/pg_setup_systemd.yml
roles/manage_efm/tasks/efm_cluster_set_params.yml
roles/manage_pgbouncer/tasks/pgbouncer_set_userlist.yml
roles/manage_pgpool2/tasks/pcp_manage_users.yml
roles/manage_pgpool2/tasks/pgpool2_manage_configuration.yml
roles/manage_pgpool2/tasks/pgpool2_manage_users.yml
roles/setup_barman/tasks/linux_update_etc_hosts.yml
roles/setup_barmanserver/tasks/linux_update_etc_hosts.yml
roles/setup_dbt2/tasks/dbt2_setup_env.yml
roles/setup_dbt2_client/tasks/main.yml
roles/setup_efm/tasks/efm_configure.yml
roles/setup_efm/tasks/efm_pgpool2_integration.yml
roles/setup_efm/tasks/linux_update_etc_hosts.yml
roles/setup_etcd/tasks/linux_update_etc_hosts.yml
roles/setup_patroni/tasks/linux_update_etc_hosts.yml
roles/setup_pemagent/tasks/linux_update_etc_hosts.yml
roles/setup_pemserver/tasks/linux_update_etc_hosts.yml
roles/setup_pgbackrest/tasks/linux_update_etc_hosts.yml
roles/setup_pgbackrestserver/tasks/generate_config.yml
roles/setup_pgbackrestserver/tasks/linux_update_etc_hosts.yml
roles/setup_pgpool2/defaults/main.yml
roles/setup_pgpool2/tasks/linux_update_etc_hosts.yml
roles/setup_replication/tasks/linux_update_etc_hosts.yml
roles/setup_replication/tasks/pg_setup_systemd.yml
roles/setup_repmgr/tasks/linux_update_etc_hosts.yml

This in-house Ansible module is intended to provide better performance than lineinfile when multiple lines must be managed.
Instead of using a loop, with linesinfile, we can pass an array of lines. This way, the module is executed only once, whatever the number of managed lines is.
Most of lineinfile's attributes are supported: line, regexp, insertafter, insertbefore, state, backrefs, firstmatch, create, owner, group, mode.
A few attributes are not supported: backup and search_string

Module linesinfile

---

plugins/modules/linesinfile.py

When the regexp matches but the content is the same, in this case we don't have to do anything.

Fix linesinfiles: do not write useless changes

---

roles/setup_pemagent/tasks/pem_agent_register_db.yml

This commit ensures the pemagent service restart after EFM and DB registration

Fix registerdb with EFM for pemagent version 9.0

---

roles/setup_repo/tasks/PG_RedHat_rm_repos.yml

In case of using wrong credentials, if we want to replace them, we first need to remove the .repo file, and then, remove the corresponding package.
If the .repo file is not removed prior to package deletion, then, package deletion is not possible due to wrong creds.
The variable force_repo must be set true.

Allow EDB credentials update

---

roles/init_dbserver/templates/postgresql.conf.template
roles/install_dbserver/defaults/main.yml
roles/install_dbserver/tasks/main.yml
roles/manage_dbserver/tasks/manage_extensions.yml
roles/setup_barman/defaults/main.yml
roles/setup_barmanserver/defaults/main.yml

Updates barman and barman-cli package version to 3.2.0-1 for EPAS to reflect the package versions offered in EDB repo. The pg-tuner package name was also updated to include Debian OS's consistent with the EDB repos. Tasks where the pg-tuner is directly called had `and ansible_os_distribution == 'RedHat'` removed from the conditional statement. Tested with EPAS and PG on Rocky8 and Debian10.

Update Barman and PG Tuner versions

---

roles/setup_repo/tasks/PG_RedHat_setuprepos.yml

Hi,
On CentOS7 default docker images, the ca-certificates package isn't updated preventing to install the pgdg package.
With the ansible role updating it to its latest version, the problem is fixed.
Kind Regards,
Stefan

[setup_repo] update ca-certificates to latest

---

roles/setup_barman/tasks/update_pg_hba.yml

In addition to @hannahms  also the fix for the default situation in task:
- name: I**nitialize the hba_entries variable** in update_pg_hba.yml
Now resulting in :
`ok: [xxxxx] => {
"msg": "[{'users': 'barman', 'databases': 'postgres', 'contype': 'hostssl', 'source': 'xxxxxx}, {'users': 'barman', 'databases': 'postgres', 'contype': 'host', 'source': 'xxxxxx'}] + [\n  {\n    'users': 'barman',\n    'databases': 'replication',\n    'contype': 'hostssl',\n    'address': '10.110.0.4/32'\n  },\n  {\n    'users': 'barman',\n    'databases': 'replication',\n    'contype': 'host',\n    'source': 'xxxxxx'\n  }\n]"
}`
Which is not correct!
Strange that the replication role has this more neat in a prepare_hba_value.yml ! Would advice to make this uninform.

addition hba appending error

---

roles/setup_barman/tasks/setup_barman.yml

When setting `barman_no_configuration: true` to skip configuration on non-primary nodes, the conditional to skip these tasks was incorrect. The following evaluates true when `barman_no_configuration: true` is set and we need to it evaluate false.
```
hostvars[inventory_hostname].barman_no_configuration is not defined
or hostvars[inventory_hostname].barman_no_configuration|bool
``` 
To have the conditional evaluate correctly, it has been changed to 
```
hostvars[inventory_hostname].barman_no_configuration is not defined
or not hostvars[inventory_hostname].barman_no_configuration|bool
```

fix barman_no_configuration logic

---

roles/setup_hammerdb/README.md
roles/setup_hammerdb/defaults/main.yml
roles/setup_hammerdb/tasks/main.yml
tests/cases/setup_hammerdb/vars.json

* Use a dedicated user for hammerdb installations as a reliable alternative to ansible_user_dir
* Add installation rules for RHEL8 and Oracle Instant Client

A couple of HammerDB playbook updates

---

roles/manage_efm/defaults/main.yml

In the `manage_efm` role, version 4.6 is missing from the `supported_efm_version` list. Now, users can go through both the `setup_efm` and `manage_efm` roles using efm v4.6.

Manage efm support for version 4.6

---

roles/setup_repo/README.md
roles/setup_repo/defaults/main.yml
roles/setup_repo/tasks/PG_Debian_setuprepos.yml
roles/setup_repo/tasks/PG_RedHat_setuprepos.yml

In cases when users have configured access to local repositories and do not require configuration of the EPEL and/or PGDG repos, the flags `enable_pgdg_repo` and `enable_epel_repo` have been added to the `setup_repo` role. When set to `false` the flags enable skipping tasks not required for configuration of the respective repo(s).

Add enable_epel_repo and enable_pgdg_repo flags

---

roles/setup_hammerdb/tasks/main.yml

This is so HammerDB can connect to PostgreSQL database systems.

Install libpq in HammerDB roles

---

roles/init_dbserver/tasks/init_dbserver.yml
roles/install_dbserver/tasks/install_dbserver.yml
roles/setup_barman/tasks/setup_barman.yml
roles/setup_barmanserver/tasks/setup_barmanserver.yml
roles/setup_dbt2/tasks/main.yml
roles/setup_dbt2_client/tasks/main.yml
roles/setup_dbt2_driver/tasks/main.yml
roles/setup_efm/tasks/setup_efm.yml
roles/setup_hammerdb/tasks/main.yml
roles/setup_pemagent/tasks/setup_pemagent.yml
roles/setup_pemserver/tasks/setup_pemserver.yml
roles/setup_pgbackrest/tasks/setup_pgbackrest.yml
roles/setup_pgbackrestserver/tasks/setup_pgbackrestserver.yml
roles/setup_pgbouncer/tasks/setup_pgbouncer.yml
roles/setup_pgpool2/tasks/setup_pgpool2.yml
roles/setup_replication/tasks/setup_replication.yml
roles/setup_repo/tasks/PG_Debian_setuprepos.yml
roles/setup_repo/tasks/PG_RedHat_rm_repos.yml
roles/setup_repo/tasks/setup_repo.yml

Adds a `remove_only` flag to all removal tasks to make allow users to run the playbook to only remove a previous attempt at or successful installation and configuration. 
Updates `rm_setup_repo` tasks to be consistent with what is currently in the respective OS family's `PG_setup_repo` installation and configuration.

Add remove_only flag and update rm_setup_repo

---

roles/setup_hammerdb/defaults/main.yml
roles/setup_hammerdb/tasks/main.yml
tests/cases/setup_hammerdb/vars.json
tests/tests/test_setup_hammerdb.py

Update HammerDB variables to support a list of versions and allow version to change without having to hardcode certain variables in the testing setup.

update hammerdb version variable setup

---

roles/init_dbserver/tasks/validate_init_dbserver.yml

pg_wal configuration check fails as `pg_wal` is empty and [we skip creating the directory](https://github.com/EnterpriseDB/edb-ansible/blob/master/roles/init_dbserver/tasks/create_directories.yml#L30-L38)
wal directory task skipped:
```yaml
TASK [edb_devops.edb_postgres.init_dbserver : Ensure postgres wal directory exists] ***
skipping: [postgres1]
```
Failing task:
```yaml
TASK [edb_devops.edb_postgres.init_dbserver : Check that pg_wal was configured correctly] ***
fatal: [postgres1]: FAILED! => {"msg": "The conditional check 'wal_check.stat['pw_name'] == pg_owner' failed. The error was: error while evaluating conditional (wal_check.stat['pw_name'] == pg_owner): 'dict object' has no attribute 'pw_name'"}
```
Ref: https://github.com/EnterpriseDB/edb-benchmarks/pull/64

fix: `pg_wal` configuration check

---

roles/install_dbserver/tasks/validate_install_dbserver.yml

`install_dbserver` role error while testing https://github.com/EnterpriseDB/edb-benchmarks/pull/64:
```yaml
TASK [edb_devops.edb_postgres.install_dbserver : Set package list for EPAS RedHat] ***
fatal: [postgres1]: FAILED! => {"msg": "Unexpected templating type error occurred on ({{ package_list | default([]) + [\n  'edb-as' + pg_version + '-server' | string, 'edb-as' + pg_version + '-server-core' | string,\n  'edb-as' + pg_version + '-server-contrib' | string, 'edb-as' + pg_version + '-server-libs' | string,\n  'edb-as' + pg_version + '-server-client' | string, 'edb-as' + pg_version + '-server-sslutils' | string,\n  'edb-as' + pg_version + '-server-indexadvisor' | string, 'edb-as' + pg_version + '-server-sqlprofiler' | string,\n  'edb-as' + pg_version + '-server-sqlprotect' | string\n] …
```

fix: convert `pg_version` to string in template

---

README.md
playbook.yml
roles/init_dbserver/README.md
roles/install_dbserver/README.md
roles/manage_cnpg/README.md
roles/manage_dbpatches/README.md
roles/manage_dbserver/README.md
roles/manage_efm/README.md
roles/manage_pgbouncer/README.md
roles/manage_pgpool2/README.md
roles/setup_barman/README.md
roles/setup_barmanserver/README.md
roles/setup_efm/README.md
roles/setup_efm/defaults/main.yml
roles/setup_efm/tasks/efm_configure.yml
roles/setup_etcd/README.md
roles/setup_patroni/README.md
roles/setup_pemagent/README.md
roles/setup_pemagent/tasks/pem_agent_install.yml
roles/setup_pemagent/tasks/setup_pemagent.yml
roles/setup_pemserver/README.md
roles/setup_pgbackrest/README.md
roles/setup_pgbackrestserver/README.md
roles/setup_pgbouncer/README.md
roles/setup_pgpool2/README.md
roles/setup_replication/README.md
roles/setup_repmgr/README.md
roles/setup_repo/README.md

- Updates `setup_pemagent` role to only have `pem_agent_fetch_adm_password.yml` run if there is no user-defined `pg_pem_admin_password`.
- Updates `setup_pemagent` role within `pem_agent_install.yml` to only have the `pg-backup-api` package installed under conditional `when: pem_server_version_int|int >= 840 and enable_pemagent_monitor_barman` instead of previous `when: pem_server_version_int|int >= 840 or enable_pemagent_monitor_barman`. The task name has also been updated to differentiate it from the `Install required packages for PEM agent` task in the same file to `Install required packages for PEM agent when enable_pemagent_monitor_barman`.
- Updates `setup_efm` role by adding the variable `efm_init_parameters` to allow users to input parameters to set at initialization. The …

Update PEM and READMEs

---

plugins/lookup/pg_conf_params_boolean.py
roles/manage_dbserver/README.md
roles/manage_dbserver/tasks/validate_manage_dbserver.yml

To ensure that boolean values are validated correctly within `pg_postgres_conf_params`, the lookup function `pg_conf_params_boolean` has been added to take boolean parameter values and return them as `on` for `true, on, yes` and `off` for `false, off, no`. The README has been updated to add comments about inputing parameter names and values as strings to make sure python parses the value correctly.

update manage_dbserver validation tasks with new lookup function

---

roles/install_dbserver/tasks/validate_install_dbserver.yml

Fixes cases within `validate_install_dbserver.yml` to separate the ssl packages and add them to `package_list` only when `pg_ssl: true`.

fix install validation to include pg_ssl

---

roles/setup_replication/tasks/validate_setup_replication.yml

Fix for #538. When running validation tasks, `use_replication_slots` flag was not included for tasks that validate the slots. The `use_replication_slots` conditional was added to tasks that validate slots to allow for `use_replication_slots: false`.

update validation for use_replication_slots (#538)

---

roles/setup_repmgr/vars/PG_Debian.yml
tests/docker/Dockerfile.debian10

Update the `PG_Debian` variable `repmgr_package_name` to not have the `pg_version` hardcoded. While fixing, the `Dockerfile.debian10` needed updating with the stretch security-updates repo. This has been archived and instead of being available at security.debian.org, it is available at archive.debian.org. This repo is required for installing the `openjdk-8-jdk` package.

Fix repmgr packages

---

roles/setup_pgbackrest/tasks/exchange_ssh_keys.yml
roles/setup_pgbackrest/tasks/validate_setup_pgbackrest.yml
roles/setup_pgbackrestserver/tasks/define_node_variables.yml
roles/setup_pgbackrestserver/tasks/generate_config.yml

Fixes error incurred in issue #537 where the variable `pgbackrest_standby_configuration` is undefined when called to loop in building the `pgbackrest_conf_lines` variable. The condition of `standby_present` was added to not build these lines when no standby is present, as the lines are only added to the configuration file if a standby is present. 
In addition this fix, the `validate_setup_pgbackrest` tasks were not working as expected. The SSH setup previously configured did not connect the pgbackrestserver to the standby in the test case. This was because of a `delegate_tasks` that had been thrown into the `exchange_ssh_keys` tasks. This line was removed. 
More commenting was added to the `define_node_variables` tasks to make each task have a unique name.

fix pgbackrest validation and configuration

---

roles/setup_pgbackrest/README.md
roles/setup_pgbackrestserver/README.md

Update pgbackrest documentation to only include playbook examples where both the `setup_pgbackrest` and `setup_pgbackrestserver` roles are included.

update pgbackrest documentation

---

roles/manage_touchstone_tools/README.md
roles/manage_touchstone_tools/defaults/main.yml
roles/manage_touchstone_tools/meta/main.yml
roles/manage_touchstone_tools/tasks/main.yml
roles/manage_touchstone_tools/tasks/manage_touchstone_tools.yml
roles/manage_touchstone_tools/tasks/plot_db_data.yml
roles/manage_touchstone_tools/tasks/plot_pidstat_data.yml
roles/manage_touchstone_tools/tasks/plot_sar_data.yml
roles/manage_touchstone_tools/tasks/process_pidstat.yml
roles/manage_touchstone_tools/tasks/start_db_stats.yml
roles/manage_touchstone_tools/tasks/start_system_stats.yml
roles/manage_touchstone_tools/tasks/stop_db_stats.yml
roles/manage_touchstone_tools/tasks/stop_system_stats.yml
roles/setup_touchstone_tools/defaults/main.yml
roles/setup_touchstone_tools/tasks/main.yml
tests/cases/manage_touchstone_tools/Makefile
tests/cases/manage_touchstone_tools/docker-compose.yml
tests/cases/manage_touchstone_tools/inventory.yml.j2
tests/cases/manage_touchstone_tools/playbook.yml
tests/cases/manage_touchstone_tools/vars.json
tests/config.yml
tests/tests/test_manage_touchstone_tools.py

Manage touchstone tools role to perform eight actions, each now contained within their own yaml file in the `manage_touchstone_tools` tasks. Each task has required variables to run, which are all specified in the README. The `manage_touchstone_tools.yml` is designed to be able to copy and paste the `import_role` block into a benchmark playbook. Examples of how to use these tasks is also documented in the README.
Within the `setup_touchstone_tools` role, I added the installation of the `fuse-sshfs` package, as that is a requirement to run the appimage in RHEL distros.

add manage_touchstone_tools

---

roles/setup_repo/tasks/PG_RedHat_setuprepos.yml
tests/cases/init_dbserver/Makefile
tests/cases/init_dbserver/docker-compose.yml
tests/cases/install_dbserver/Makefile
tests/cases/install_dbserver/docker-compose.yml

No powertools repo available in RedHat8, equivalent would be to run `sudo subscription-manager repos --enable codeready-builder-for-rhel-8-x86_64-rpms` but with the UBI base-image used, there is no subscription to manage. The rest of the tasks work as the powertools/codeready builder repo does not prohibit the EPEL repo in RedHat8.

update powertools for RedHat8

---

roles/setup_repo/tasks/PG_Debian_setuprepos.yml
roles/setup_repo/tasks/PG_RedHat_setuprepos.yml
roles/setup_repo/tasks/validate_setup_repo.yml

The `repo_token|length = 1` when `repo_token` is set to `""` within the test cases, causing the install and validation to fail. This fixes those issues.

fix repo token length for test cases

---

meta/runtime.yml

There is a bug in ansible 2.10 where rocky systems are not recognized to be within the `RedHat ansible_os_family`. This bug is fixed in ansible 2.11.

update minimum ansible version to 2.11

---

roles/install_dbserver/tasks/EPAS_Debian_install.yml
roles/install_dbserver/tasks/EPAS_Debian_rm_install.yml
roles/install_dbserver/tasks/EPAS_RedHat_install.yml
roles/install_dbserver/tasks/EPAS_RedHat_rm_install.yml
roles/install_dbserver/tasks/PG_Debian_install.yml
roles/install_dbserver/tasks/PG_RedHat_install.yml
roles/install_dbserver/tasks/validate_install_dbserver.yml
roles/setup_repo/tasks/PG_Debian_setuprepos.yml
roles/setup_repo/tasks/PG_RedHat_setuprepos.yml
roles/setup_repo/tasks/validate_setup_repo.yml
tests/tests/test_install_dbserver.py

Fixes EPAS <= 13 package validation of `edb-as1x-server-edb-modules, which installs `edb-as1x-server-edb_wait_states` on RedHat only, to recognize the `edb_wait_states` package instead of the `edb-modules` package. 
Also fixes within the `setup_repo` role, when no `repo_token` is provided in the new testing setup, which allows users to optionally pass a repo token in, it sees the `repo_token` variable as a blank string of length 1. To accurately not skip over these tasks, the conditional has been made inclusive of 1 instead of exclusive of 1.

fix edb_wait_states for RH EPAS13 and fix new repo token testing

---

roles/setup_dbt2/tasks/dbt2_install_packages_driver.yml

These are provided by the dbt2 appimage.  No longer need to install them separately.

setup_dbt2: remove flame graph installation

---

roles/setup_dbt2/tasks/dbt2_update_pg_hba.yml

There are cases where dbt2 scripts may access the primary database system by its private ip address locally.  Make sure it's allowed.

setup_dbt2: add primary database ip to pg_hba.conf

---

roles/manage_dbserver/handlers/main.yml
roles/setup_patroni/tasks/patroni_generate_basic_passwords.yml
roles/setup_patroni/tasks/patroni_set_user_passwords_privs.yml
roles/setup_patroni/tasks/primary_synchronous_param.yml
roles/setup_patroni/tasks/setup_patroni.yml
roles/setup_patroni/tasks/validate_setup_patroni.yml
roles/setup_patroni/templates/patroni.config.yml.j2
roles/setup_patroni/templates/postgresql.conf.template

made some minor updates to ensure Patroni is running smoothly while benchmarking. 
- Updated `manage_dbserver/handlers/main.yml` to include a `become: true` parameter; this is required because the parameter `daemon_reload: true` requires root priviliges. 
- Updated `patroni.config.yml.j2` to set the postgresql `listen: "*"` as this parameter must match the `listen_addresses = '*'` parameter set in `postgresql.auto.conf` otherwise Patroni thinks you are trying to change the listen address.
- Updated `postgresql.conf.template` to sync up the `wal_level: logical` set in `patroni.config.yml.j2` and now is a default in the `init_dbserver` role. 
- Added `run_once: true` to more validate tasks and tasks within `patroni_generate_basic_password.yml` and `patroni_set_user_password_privs.yml`.
- …

minor updates to ensure patroni running smoothly

---

roles/init_dbserver/tasks/validate_init_dbserver.yml
roles/setup_etcd/README.md
roles/setup_patroni/defaults/main.yml
roles/setup_patroni/tasks/patroni_generate_basic_passwords.yml
roles/setup_patroni/tasks/primary_synchronous_param.yml
roles/setup_patroni/tasks/validate_setup_patroni.yml
roles/setup_patroni/templates/patroni.config.yml.j2
tests/cases/setup_patroni/vars.json

- Fixes some run errors from wrong changes yesterday - reverting by removing `run_once: true`
- Add pg_basebackup options to Patroni config file - task was timing out and causing the setup to fail and added the `- checkpoint: ‘fast’` to run the basebackup faster
- Documented changes in code

More patroni setup

---

roles/setup_patroni/README.md
roles/setup_patroni/defaults/main.yml
roles/setup_patroni/tasks/patroni_configure.yml
roles/setup_patroni/templates/patroni.config.yml.j2
tests/cases/setup_patroni/vars.json

Certain postgres parameters must be set in the Patroni configuration file otherwise they will be overridden by Patroni default values. To allow customization of these parameters, the `patroni_pg_init_params` variable is added and the parameters listed, if any, are included in the PostgreSQL parameters section of the Patroni config file. 
The README has been updated to include information about the default settings, how and why to customize, what the resulting setting will look like in the config file, and links back to the Patroni documentation _Patroni configuation important rules_.
Under the `basebackup` method section in the Patroni config file, the `--create-slot` and `--slot inventory_hostname` `pg_basebackup` parameters have also been added because the log file showed it was …

add dynamic postgres params in patroni config

---

roles/setup_dbt2/tasks/dbt2_configure_pgpass.yml

Updates `setup_dbt2/dbt2_configure_pgpass.yml` to use `manage_dbserver/manage_pgpass` tasks to update the `~/.pgpass` file when it already exists. This keeps the DBT-2 role from overriding already configured values within the DB server pgpass. 
Keeps `azure_db_hackery` parameters.

update dbt2 pgpass

---

roles/setup_dbt2/tasks/dbt2_configure_pgpass.yml
roles/setup_dbt2/templates/pgpass.template

Fix two issues:
Don't overwrite an exist .pgpass file.  This playbook previously wasn't taking into consideration that the .pgpass file it is editing was already exist of not, always override it with a template.  Using ansible.builtin.lineinfile is hopefully the best way to handle that.
Don't assume we're not a DBaaS system.  manage_dbserver playbooks will fail if we're setting up a system that is testing a DBaaS database.  The ansible.builtin.lineinfile task should be able to handle both cases appropriates.

setup_dbt2 dbt2_configure_pgpass: fix logic

---

roles/setup_pgd/defaults/main.yml

The default value for pgd_commit_scopes should be an empty list as opposed to an empty string because all of the validations are written for lists as opposed to strings.

setup_pgd pgd_commit_scopes default empty list

---

tests/scripts/lib/docker.py

Corrects json parsing error caused by breaking change in docker-compose 2.21.

update docker.py for docker-compose 2.21 breaking changes

---

roles/manage_operating_system/README.md
roles/manage_operating_system/defaults/main.yml
roles/manage_operating_system/meta/main.yml
roles/manage_operating_system/tasks/disable_user_profiling.yml
roles/manage_operating_system/tasks/enable_user_profiling.yml
roles/manage_operating_system/tasks/main.yml

This role is for managing operating system tasks.  The first task included is to enable profiling for unprivileged users.

Add manage_operating_system role

---

roles/setup_dbt2/tasks/dbt2_install_packages_client.yml
roles/setup_dbt2/tasks/dbt2_install_packages_db.yml
roles/setup_dbt2/tasks/dbt2_install_packages_driver.yml
roles/setup_touchstone_tools/tasks/main.yml

gnuplot in the AppImages rely on fontconfig and some fonts to be installed on the system.

install fonts for appimages

---

roles/manage_operating_system/tasks/enable_core_dump.yml
roles/setup_dbt2/tasks/validate_setup_dbt2.yml

* clear out potential kernel.core_pattern conflicts from tpaexec
* install systemd-coredump on debian based distros

core dump related updates

---

roles/manage_dbserver/tasks/manage_postgres_params.yml
roles/setup_etcd/defaults/main.yml
roles/setup_etcd/tasks/etcd_install.yml
roles/setup_etcd/tasks/etcd_ssl_member_key.yml
roles/setup_etcd/tasks/etcd_user_group.yml
roles/setup_etcd/tasks/setup_etcd.yml
roles/setup_etcd/vars/EPAS_Debian.yml
roles/setup_etcd/vars/EPAS_RedHat.yml
roles/setup_etcd/vars/PG_Debian.yml
roles/setup_etcd/vars/PG_RedHat.yml

- Update with [issue #611](https://github.com/EnterpriseDB/edb-ansible/issues/611) informations
- Fix `manage_postgres_params.yml` reload vs restart logic to reload only when no restart required

Fix etcd patroni

---

roles/setup_pgbackrest/README.md
roles/setup_pgbackrest/defaults/main.yml
roles/setup_pgbackrest/tasks/configure_pg_backup.yml
roles/setup_pgbackrest/tasks/configure_pgbackrest.yml
roles/setup_pgbackrest/tasks/define_node_variables.yml
roles/setup_pgbackrest/tasks/generate_ssh_keys.yml
roles/setup_pgbackrest/tasks/post_configure_pgbackrest.yml
roles/setup_pgbackrest/tasks/setup_pgbackrest.yml
roles/setup_pgbackrest/tasks/validate_setup_pgbackrest.yml
roles/setup_pgbackrest/templates/pgbackrest_primary.async.conf.template
roles/setup_pgbackrest/templates/pgbackrest_primary.standard.conf.template
roles/setup_pgbackrest/templates/pgbackrest_standby.async.conf.template
roles/setup_pgbackrest/templates/pgbackrest_standby.standard.conf.template
roles/setup_pgbackrestserver/defaults/main.yml
roles/setup_pgbackrestserver/tasks/define_node_variables.yml
roles/setup_pgbackrestserver/tasks/generate_config.yml
roles/setup_pgbackrestserver/templates/pgbackrest.conf.template

- fix pg_data setup causing issues in config files
- fix public/private IP as hostname
- condense some `use_hostname` vs. `not use_hostname` tasks

fix pgbackrest configuration

---

roles/setup_pgbackrest/tasks/rm_pgbackrest_install_config.yml
roles/setup_pgbackrestserver/tasks/pgbackrest_install_EPAS.yml
roles/setup_pgbackrestserver/tasks/rm_pgbackrestserver_install_config.yml
roles/setup_repo/defaults/main.yml

The current path for the PostgreSQL yum repository GPG key is invalid, and returns a 404 error: http://yum.postgresql.org/RPM-GPG-KEY-PGDG
The key is in fact at: http://yum.postgresql.org/keys/RPM-GPG-KEY-PGDG
This patch fixes that.

Fix yum.postgresql.org repository GPG key path

---

roles/setup_pgbackrest/tasks/configure_pgbackrest.yml

When using the same server for both primary and pgbackrestserver roles, pgbackrest role will fail with following error :
```
Could not find or access
'./templates/pgbackrest_pgbackrestserver.async.conf.template'
```
This is due to server belonging to both 'pgbackrestserver' and 'primary' inventory groups.

force pgbackrest template config file name

---

plugins/lookup/barman_server.py
plugins/lookup/dbt2_client.py
plugins/lookup/efm_nodes.py
plugins/lookup/etcd_cluster_nodes.py
plugins/lookup/hammerdb.py
plugins/lookup/haproxy_backends.py
plugins/lookup/pem_agents.py
plugins/lookup/pem_server.py
plugins/lookup/pg_service.py
plugins/lookup/pg_sr_cluster_nodes.py
plugins/lookup/pgbackrest_nodes.py
plugins/lookup/pgbackrest_server.py
plugins/lookup/pgd_lead_primary.py
plugins/lookup/pgd_nodes.py
plugins/lookup/pgpool2_nodes.py
plugins/lookup/repmgr_nodes.py

When ansible_host is defined in an inventory file in the .ini format, ansible is unable to retrieve the value and fails with following error:
TASK [edb_devops.edb_postgres.setup_replication : Gather the cluster_nodes information] ************************************************************************************************************* task path: /home/user/.ansible/collections/ansible_collections/edb_devops/edb_postgres/roles/setup_replication/tasks/setup_replication.yml:51 fatal: [hostname]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'edb_devops.edb_postgres.pg_sr_cluster_nodes'. Error was a <class 'KeyError'>, original message: 'ansible_host'. 'ansible_host'"}
inventory example:
```
[primary]
primary1 ansible_host=primary1 private_ip=x.x.x.1 …
```

fix class KeyError original message: ansible_host

---

roles/setup_repo/README.md
roles/setup_repo/defaults/main.yml

This is in addition to the current support for the enterprise plan, and makes it configurable, with the default remaining enterprise.
Addresses #619.

Add support for standard EDB subscription plan for repo script download

---

roles/setup_pgpool2/defaults/main.yml
roles/setup_pgpool2/tasks/pgpool2_configure_backends.yml

Leaving the default as `ALLOW_TO_FAILOVER`.

Make pgpool2 backend flag configurable

---

roles/setup_pgbackrest/tasks/configure_pgbackrest.yml
roles/tuning/tasks/tune_postgres.yml

These were introduced at #617 and prevents all checks from succeeding.

Fix linting issues due to long lines and improper spacing

---

roles/install_dbserver/tasks/PG_RedHat_rm_install.yml

When removing python3-SELinux package the firewalld package is removed too. there is a dependency with the firewalld package

Prevent firewall.d removal
